// Code generated by ent, DO NOT EDIT.

package fieldvalue

import (
	"papergo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldCreatedAt, v))
}

// SurfaceID applies equality check predicate on the "surface_id" field. It's identical to SurfaceIDEQ.
func SurfaceID(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldSurfaceID, v))
}

// ContainerID applies equality check predicate on the "container_id" field. It's identical to ContainerIDEQ.
func ContainerID(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldContainerID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldItemID, v))
}

// FieldKey applies equality check predicate on the "field_key" field. It's identical to FieldKeyEQ.
func FieldKey(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldFieldKey, v))
}

// Ordinal applies equality check predicate on the "ordinal" field. It's identical to OrdinalEQ.
func Ordinal(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldOrdinal, v))
}

// Scale applies equality check predicate on the "scale" field. It's identical to ScaleEQ.
func Scale(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldScale, v))
}

// ValueText applies equality check predicate on the "value_text" field. It's identical to ValueTextEQ.
func ValueText(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueText, v))
}

// ValueInteger applies equality check predicate on the "value_integer" field. It's identical to ValueIntegerEQ.
func ValueInteger(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueInteger, v))
}

// ValueNumber applies equality check predicate on the "value_number" field. It's identical to ValueNumberEQ.
func ValueNumber(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueNumber, v))
}

// ValueBoolean applies equality check predicate on the "value_boolean" field. It's identical to ValueBooleanEQ.
func ValueBoolean(v bool) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueBoolean, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldCreatedAt, v))
}

// SurfaceIDEQ applies the EQ predicate on the "surface_id" field.
func SurfaceIDEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldSurfaceID, v))
}

// SurfaceIDNEQ applies the NEQ predicate on the "surface_id" field.
func SurfaceIDNEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldSurfaceID, v))
}

// SurfaceIDIn applies the In predicate on the "surface_id" field.
func SurfaceIDIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldSurfaceID, vs...))
}

// SurfaceIDNotIn applies the NotIn predicate on the "surface_id" field.
func SurfaceIDNotIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldSurfaceID, vs...))
}

// SurfaceIDGT applies the GT predicate on the "surface_id" field.
func SurfaceIDGT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldSurfaceID, v))
}

// SurfaceIDGTE applies the GTE predicate on the "surface_id" field.
func SurfaceIDGTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldSurfaceID, v))
}

// SurfaceIDLT applies the LT predicate on the "surface_id" field.
func SurfaceIDLT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldSurfaceID, v))
}

// SurfaceIDLTE applies the LTE predicate on the "surface_id" field.
func SurfaceIDLTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldSurfaceID, v))
}

// SurfaceIDContains applies the Contains predicate on the "surface_id" field.
func SurfaceIDContains(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContains(FieldSurfaceID, v))
}

// SurfaceIDHasPrefix applies the HasPrefix predicate on the "surface_id" field.
func SurfaceIDHasPrefix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasPrefix(FieldSurfaceID, v))
}

// SurfaceIDHasSuffix applies the HasSuffix predicate on the "surface_id" field.
func SurfaceIDHasSuffix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasSuffix(FieldSurfaceID, v))
}

// SurfaceIDEqualFold applies the EqualFold predicate on the "surface_id" field.
func SurfaceIDEqualFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEqualFold(FieldSurfaceID, v))
}

// SurfaceIDContainsFold applies the ContainsFold predicate on the "surface_id" field.
func SurfaceIDContainsFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContainsFold(FieldSurfaceID, v))
}

// ContainerIDEQ applies the EQ predicate on the "container_id" field.
func ContainerIDEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldContainerID, v))
}

// ContainerIDNEQ applies the NEQ predicate on the "container_id" field.
func ContainerIDNEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldContainerID, v))
}

// ContainerIDIn applies the In predicate on the "container_id" field.
func ContainerIDIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldContainerID, vs...))
}

// ContainerIDNotIn applies the NotIn predicate on the "container_id" field.
func ContainerIDNotIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldContainerID, vs...))
}

// ContainerIDGT applies the GT predicate on the "container_id" field.
func ContainerIDGT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldContainerID, v))
}

// ContainerIDGTE applies the GTE predicate on the "container_id" field.
func ContainerIDGTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldContainerID, v))
}

// ContainerIDLT applies the LT predicate on the "container_id" field.
func ContainerIDLT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldContainerID, v))
}

// ContainerIDLTE applies the LTE predicate on the "container_id" field.
func ContainerIDLTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldContainerID, v))
}

// ContainerIDContains applies the Contains predicate on the "container_id" field.
func ContainerIDContains(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContains(FieldContainerID, v))
}

// ContainerIDHasPrefix applies the HasPrefix predicate on the "container_id" field.
func ContainerIDHasPrefix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasPrefix(FieldContainerID, v))
}

// ContainerIDHasSuffix applies the HasSuffix predicate on the "container_id" field.
func ContainerIDHasSuffix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasSuffix(FieldContainerID, v))
}

// ContainerIDEqualFold applies the EqualFold predicate on the "container_id" field.
func ContainerIDEqualFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEqualFold(FieldContainerID, v))
}

// ContainerIDContainsFold applies the ContainsFold predicate on the "container_id" field.
func ContainerIDContainsFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContainsFold(FieldContainerID, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldItemID, v))
}

// ItemIDContains applies the Contains predicate on the "item_id" field.
func ItemIDContains(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContains(FieldItemID, v))
}

// ItemIDHasPrefix applies the HasPrefix predicate on the "item_id" field.
func ItemIDHasPrefix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasPrefix(FieldItemID, v))
}

// ItemIDHasSuffix applies the HasSuffix predicate on the "item_id" field.
func ItemIDHasSuffix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasSuffix(FieldItemID, v))
}

// ItemIDEqualFold applies the EqualFold predicate on the "item_id" field.
func ItemIDEqualFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEqualFold(FieldItemID, v))
}

// ItemIDContainsFold applies the ContainsFold predicate on the "item_id" field.
func ItemIDContainsFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContainsFold(FieldItemID, v))
}

// SurfaceEQ applies the EQ predicate on the "surface" field.
func SurfaceEQ(v Surface) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldSurface, v))
}

// SurfaceNEQ applies the NEQ predicate on the "surface" field.
func SurfaceNEQ(v Surface) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldSurface, v))
}

// SurfaceIn applies the In predicate on the "surface" field.
func SurfaceIn(vs ...Surface) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldSurface, vs...))
}

// SurfaceNotIn applies the NotIn predicate on the "surface" field.
func SurfaceNotIn(vs ...Surface) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldSurface, vs...))
}

// FieldKeyEQ applies the EQ predicate on the "field_key" field.
func FieldKeyEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldFieldKey, v))
}

// FieldKeyNEQ applies the NEQ predicate on the "field_key" field.
func FieldKeyNEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldFieldKey, v))
}

// FieldKeyIn applies the In predicate on the "field_key" field.
func FieldKeyIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldFieldKey, vs...))
}

// FieldKeyNotIn applies the NotIn predicate on the "field_key" field.
func FieldKeyNotIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldFieldKey, vs...))
}

// FieldKeyGT applies the GT predicate on the "field_key" field.
func FieldKeyGT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldFieldKey, v))
}

// FieldKeyGTE applies the GTE predicate on the "field_key" field.
func FieldKeyGTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldFieldKey, v))
}

// FieldKeyLT applies the LT predicate on the "field_key" field.
func FieldKeyLT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldFieldKey, v))
}

// FieldKeyLTE applies the LTE predicate on the "field_key" field.
func FieldKeyLTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldFieldKey, v))
}

// FieldKeyContains applies the Contains predicate on the "field_key" field.
func FieldKeyContains(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContains(FieldFieldKey, v))
}

// FieldKeyHasPrefix applies the HasPrefix predicate on the "field_key" field.
func FieldKeyHasPrefix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasPrefix(FieldFieldKey, v))
}

// FieldKeyHasSuffix applies the HasSuffix predicate on the "field_key" field.
func FieldKeyHasSuffix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasSuffix(FieldFieldKey, v))
}

// FieldKeyEqualFold applies the EqualFold predicate on the "field_key" field.
func FieldKeyEqualFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEqualFold(FieldFieldKey, v))
}

// FieldKeyContainsFold applies the ContainsFold predicate on the "field_key" field.
func FieldKeyContainsFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContainsFold(FieldFieldKey, v))
}

// FieldTypeEQ applies the EQ predicate on the "field_type" field.
func FieldTypeEQ(v FieldType) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldFieldType, v))
}

// FieldTypeNEQ applies the NEQ predicate on the "field_type" field.
func FieldTypeNEQ(v FieldType) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldFieldType, v))
}

// FieldTypeIn applies the In predicate on the "field_type" field.
func FieldTypeIn(vs ...FieldType) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldFieldType, vs...))
}

// FieldTypeNotIn applies the NotIn predicate on the "field_type" field.
func FieldTypeNotIn(vs ...FieldType) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldFieldType, vs...))
}

// OrdinalEQ applies the EQ predicate on the "ordinal" field.
func OrdinalEQ(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldOrdinal, v))
}

// OrdinalNEQ applies the NEQ predicate on the "ordinal" field.
func OrdinalNEQ(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldOrdinal, v))
}

// OrdinalIn applies the In predicate on the "ordinal" field.
func OrdinalIn(vs ...int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldOrdinal, vs...))
}

// OrdinalNotIn applies the NotIn predicate on the "ordinal" field.
func OrdinalNotIn(vs ...int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldOrdinal, vs...))
}

// OrdinalGT applies the GT predicate on the "ordinal" field.
func OrdinalGT(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldOrdinal, v))
}

// OrdinalGTE applies the GTE predicate on the "ordinal" field.
func OrdinalGTE(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldOrdinal, v))
}

// OrdinalLT applies the LT predicate on the "ordinal" field.
func OrdinalLT(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldOrdinal, v))
}

// OrdinalLTE applies the LTE predicate on the "ordinal" field.
func OrdinalLTE(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldOrdinal, v))
}

// ScaleEQ applies the EQ predicate on the "scale" field.
func ScaleEQ(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldScale, v))
}

// ScaleNEQ applies the NEQ predicate on the "scale" field.
func ScaleNEQ(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldScale, v))
}

// ScaleIn applies the In predicate on the "scale" field.
func ScaleIn(vs ...int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldScale, vs...))
}

// ScaleNotIn applies the NotIn predicate on the "scale" field.
func ScaleNotIn(vs ...int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldScale, vs...))
}

// ScaleGT applies the GT predicate on the "scale" field.
func ScaleGT(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldScale, v))
}

// ScaleGTE applies the GTE predicate on the "scale" field.
func ScaleGTE(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldScale, v))
}

// ScaleLT applies the LT predicate on the "scale" field.
func ScaleLT(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldScale, v))
}

// ScaleLTE applies the LTE predicate on the "scale" field.
func ScaleLTE(v int) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldScale, v))
}

// ValueTextEQ applies the EQ predicate on the "value_text" field.
func ValueTextEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueText, v))
}

// ValueTextNEQ applies the NEQ predicate on the "value_text" field.
func ValueTextNEQ(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldValueText, v))
}

// ValueTextIn applies the In predicate on the "value_text" field.
func ValueTextIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldValueText, vs...))
}

// ValueTextNotIn applies the NotIn predicate on the "value_text" field.
func ValueTextNotIn(vs ...string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldValueText, vs...))
}

// ValueTextGT applies the GT predicate on the "value_text" field.
func ValueTextGT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldValueText, v))
}

// ValueTextGTE applies the GTE predicate on the "value_text" field.
func ValueTextGTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldValueText, v))
}

// ValueTextLT applies the LT predicate on the "value_text" field.
func ValueTextLT(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldValueText, v))
}

// ValueTextLTE applies the LTE predicate on the "value_text" field.
func ValueTextLTE(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldValueText, v))
}

// ValueTextContains applies the Contains predicate on the "value_text" field.
func ValueTextContains(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContains(FieldValueText, v))
}

// ValueTextHasPrefix applies the HasPrefix predicate on the "value_text" field.
func ValueTextHasPrefix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasPrefix(FieldValueText, v))
}

// ValueTextHasSuffix applies the HasSuffix predicate on the "value_text" field.
func ValueTextHasSuffix(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldHasSuffix(FieldValueText, v))
}

// ValueTextIsNil applies the IsNil predicate on the "value_text" field.
func ValueTextIsNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIsNull(FieldValueText))
}

// ValueTextNotNil applies the NotNil predicate on the "value_text" field.
func ValueTextNotNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotNull(FieldValueText))
}

// ValueTextEqualFold applies the EqualFold predicate on the "value_text" field.
func ValueTextEqualFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEqualFold(FieldValueText, v))
}

// ValueTextContainsFold applies the ContainsFold predicate on the "value_text" field.
func ValueTextContainsFold(v string) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldContainsFold(FieldValueText, v))
}

// ValueIntegerEQ applies the EQ predicate on the "value_integer" field.
func ValueIntegerEQ(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueInteger, v))
}

// ValueIntegerNEQ applies the NEQ predicate on the "value_integer" field.
func ValueIntegerNEQ(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldValueInteger, v))
}

// ValueIntegerIn applies the In predicate on the "value_integer" field.
func ValueIntegerIn(vs ...int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldValueInteger, vs...))
}

// ValueIntegerNotIn applies the NotIn predicate on the "value_integer" field.
func ValueIntegerNotIn(vs ...int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldValueInteger, vs...))
}

// ValueIntegerGT applies the GT predicate on the "value_integer" field.
func ValueIntegerGT(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldValueInteger, v))
}

// ValueIntegerGTE applies the GTE predicate on the "value_integer" field.
func ValueIntegerGTE(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldValueInteger, v))
}

// ValueIntegerLT applies the LT predicate on the "value_integer" field.
func ValueIntegerLT(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldValueInteger, v))
}

// ValueIntegerLTE applies the LTE predicate on the "value_integer" field.
func ValueIntegerLTE(v int64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldValueInteger, v))
}

// ValueIntegerIsNil applies the IsNil predicate on the "value_integer" field.
func ValueIntegerIsNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIsNull(FieldValueInteger))
}

// ValueIntegerNotNil applies the NotNil predicate on the "value_integer" field.
func ValueIntegerNotNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotNull(FieldValueInteger))
}

// ValueNumberEQ applies the EQ predicate on the "value_number" field.
func ValueNumberEQ(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueNumber, v))
}

// ValueNumberNEQ applies the NEQ predicate on the "value_number" field.
func ValueNumberNEQ(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldValueNumber, v))
}

// ValueNumberIn applies the In predicate on the "value_number" field.
func ValueNumberIn(vs ...float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIn(FieldValueNumber, vs...))
}

// ValueNumberNotIn applies the NotIn predicate on the "value_number" field.
func ValueNumberNotIn(vs ...float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotIn(FieldValueNumber, vs...))
}

// ValueNumberGT applies the GT predicate on the "value_number" field.
func ValueNumberGT(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGT(FieldValueNumber, v))
}

// ValueNumberGTE applies the GTE predicate on the "value_number" field.
func ValueNumberGTE(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldGTE(FieldValueNumber, v))
}

// ValueNumberLT applies the LT predicate on the "value_number" field.
func ValueNumberLT(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLT(FieldValueNumber, v))
}

// ValueNumberLTE applies the LTE predicate on the "value_number" field.
func ValueNumberLTE(v float64) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldLTE(FieldValueNumber, v))
}

// ValueNumberIsNil applies the IsNil predicate on the "value_number" field.
func ValueNumberIsNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIsNull(FieldValueNumber))
}

// ValueNumberNotNil applies the NotNil predicate on the "value_number" field.
func ValueNumberNotNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotNull(FieldValueNumber))
}

// ValueBooleanEQ applies the EQ predicate on the "value_boolean" field.
func ValueBooleanEQ(v bool) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldEQ(FieldValueBoolean, v))
}

// ValueBooleanNEQ applies the NEQ predicate on the "value_boolean" field.
func ValueBooleanNEQ(v bool) predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNEQ(FieldValueBoolean, v))
}

// ValueBooleanIsNil applies the IsNil predicate on the "value_boolean" field.
func ValueBooleanIsNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldIsNull(FieldValueBoolean))
}

// ValueBooleanNotNil applies the NotNil predicate on the "value_boolean" field.
func ValueBooleanNotNil() predicate.FieldValue {
	return predicate.FieldValue(sql.FieldNotNull(FieldValueBoolean))
}

// HasItemSurface applies the HasEdge predicate on the "item_surface" edge.
func HasItemSurface() predicate.FieldValue {
	return predicate.FieldValue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ItemSurfaceTable, ItemSurfaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemSurfaceWith applies the HasEdge predicate on the "item_surface" edge with a given conditions (other predicates).
func HasItemSurfaceWith(preds ...predicate.ItemSurface) predicate.FieldValue {
	return predicate.FieldValue(func(s *sql.Selector) {
		step := newItemSurfaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FieldValue) predicate.FieldValue {
	return predicate.FieldValue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FieldValue) predicate.FieldValue {
	return predicate.FieldValue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FieldValue) predicate.FieldValue {
	return predicate.FieldValue(sql.NotPredicates(p))
}
