// Code generated by ent, DO NOT EDIT.

package workflowrun

import (
	"papergo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreatedAt, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowVersion applies equality check predicate on the "workflow_version" field. It's identical to WorkflowVersionEQ.
func WorkflowVersion(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldWorkflowVersion, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldWorkspaceID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldItemID, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldEventID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldEventType, v))
}

// Depth applies equality check predicate on the "depth" field. It's identical to DepthEQ.
func Depth(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldDepth, v))
}

// Actor applies equality check predicate on the "actor" field. It's identical to ActorEQ.
func Actor(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldActor, v))
}

// RetryOf applies equality check predicate on the "retry_of" field. It's identical to RetryOfEQ.
func RetryOf(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldRetryOf, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldCreatedAt, v))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowIDGT applies the GT predicate on the "workflow_id" field.
func WorkflowIDGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldWorkflowID, v))
}

// WorkflowIDGTE applies the GTE predicate on the "workflow_id" field.
func WorkflowIDGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldWorkflowID, v))
}

// WorkflowIDLT applies the LT predicate on the "workflow_id" field.
func WorkflowIDLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldWorkflowID, v))
}

// WorkflowIDLTE applies the LTE predicate on the "workflow_id" field.
func WorkflowIDLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldWorkflowID, v))
}

// WorkflowIDContains applies the Contains predicate on the "workflow_id" field.
func WorkflowIDContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldWorkflowID, v))
}

// WorkflowIDHasPrefix applies the HasPrefix predicate on the "workflow_id" field.
func WorkflowIDHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldWorkflowID, v))
}

// WorkflowIDHasSuffix applies the HasSuffix predicate on the "workflow_id" field.
func WorkflowIDHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldWorkflowID, v))
}

// WorkflowIDEqualFold applies the EqualFold predicate on the "workflow_id" field.
func WorkflowIDEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldWorkflowID, v))
}

// WorkflowIDContainsFold applies the ContainsFold predicate on the "workflow_id" field.
func WorkflowIDContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldWorkflowID, v))
}

// WorkflowVersionEQ applies the EQ predicate on the "workflow_version" field.
func WorkflowVersionEQ(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldWorkflowVersion, v))
}

// WorkflowVersionNEQ applies the NEQ predicate on the "workflow_version" field.
func WorkflowVersionNEQ(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldWorkflowVersion, v))
}

// WorkflowVersionIn applies the In predicate on the "workflow_version" field.
func WorkflowVersionIn(vs ...int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldWorkflowVersion, vs...))
}

// WorkflowVersionNotIn applies the NotIn predicate on the "workflow_version" field.
func WorkflowVersionNotIn(vs ...int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldWorkflowVersion, vs...))
}

// WorkflowVersionGT applies the GT predicate on the "workflow_version" field.
func WorkflowVersionGT(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldWorkflowVersion, v))
}

// WorkflowVersionGTE applies the GTE predicate on the "workflow_version" field.
func WorkflowVersionGTE(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldWorkflowVersion, v))
}

// WorkflowVersionLT applies the LT predicate on the "workflow_version" field.
func WorkflowVersionLT(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldWorkflowVersion, v))
}

// WorkflowVersionLTE applies the LTE predicate on the "workflow_version" field.
func WorkflowVersionLTE(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldWorkflowVersion, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldWorkspaceID, v))
}

// WorkspaceIDContains applies the Contains predicate on the "workspace_id" field.
func WorkspaceIDContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldWorkspaceID, v))
}

// WorkspaceIDHasPrefix applies the HasPrefix predicate on the "workspace_id" field.
func WorkspaceIDHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldWorkspaceID, v))
}

// WorkspaceIDHasSuffix applies the HasSuffix predicate on the "workspace_id" field.
func WorkspaceIDHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldWorkspaceID, v))
}

// WorkspaceIDEqualFold applies the EqualFold predicate on the "workspace_id" field.
func WorkspaceIDEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldWorkspaceID, v))
}

// WorkspaceIDContainsFold applies the ContainsFold predicate on the "workspace_id" field.
func WorkspaceIDContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldWorkspaceID, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldItemID, v))
}

// ItemIDContains applies the Contains predicate on the "item_id" field.
func ItemIDContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldItemID, v))
}

// ItemIDHasPrefix applies the HasPrefix predicate on the "item_id" field.
func ItemIDHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldItemID, v))
}

// ItemIDHasSuffix applies the HasSuffix predicate on the "item_id" field.
func ItemIDHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldItemID, v))
}

// ItemIDIsNil applies the IsNil predicate on the "item_id" field.
func ItemIDIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldItemID))
}

// ItemIDNotNil applies the NotNil predicate on the "item_id" field.
func ItemIDNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldItemID))
}

// ItemIDEqualFold applies the EqualFold predicate on the "item_id" field.
func ItemIDEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldItemID, v))
}

// ItemIDContainsFold applies the ContainsFold predicate on the "item_id" field.
func ItemIDContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldItemID, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldEventID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldEventType, v))
}

// DepthEQ applies the EQ predicate on the "depth" field.
func DepthEQ(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldDepth, v))
}

// DepthNEQ applies the NEQ predicate on the "depth" field.
func DepthNEQ(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldDepth, v))
}

// DepthIn applies the In predicate on the "depth" field.
func DepthIn(vs ...int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldDepth, vs...))
}

// DepthNotIn applies the NotIn predicate on the "depth" field.
func DepthNotIn(vs ...int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldDepth, vs...))
}

// DepthGT applies the GT predicate on the "depth" field.
func DepthGT(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldDepth, v))
}

// DepthGTE applies the GTE predicate on the "depth" field.
func DepthGTE(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldDepth, v))
}

// DepthLT applies the LT predicate on the "depth" field.
func DepthLT(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldDepth, v))
}

// DepthLTE applies the LTE predicate on the "depth" field.
func DepthLTE(v int) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldDepth, v))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldActor, vs...))
}

// ActorGT applies the GT predicate on the "actor" field.
func ActorGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldActor, v))
}

// ActorGTE applies the GTE predicate on the "actor" field.
func ActorGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldActor, v))
}

// ActorLT applies the LT predicate on the "actor" field.
func ActorLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldActor, v))
}

// ActorLTE applies the LTE predicate on the "actor" field.
func ActorLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldActor, v))
}

// ActorContains applies the Contains predicate on the "actor" field.
func ActorContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldActor, v))
}

// ActorHasPrefix applies the HasPrefix predicate on the "actor" field.
func ActorHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldActor, v))
}

// ActorHasSuffix applies the HasSuffix predicate on the "actor" field.
func ActorHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldActor, v))
}

// ActorEqualFold applies the EqualFold predicate on the "actor" field.
func ActorEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldActor, v))
}

// ActorContainsFold applies the ContainsFold predicate on the "actor" field.
func ActorContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldActor, v))
}

// RetryOfEQ applies the EQ predicate on the "retry_of" field.
func RetryOfEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldRetryOf, v))
}

// RetryOfNEQ applies the NEQ predicate on the "retry_of" field.
func RetryOfNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldRetryOf, v))
}

// RetryOfIn applies the In predicate on the "retry_of" field.
func RetryOfIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldRetryOf, vs...))
}

// RetryOfNotIn applies the NotIn predicate on the "retry_of" field.
func RetryOfNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldRetryOf, vs...))
}

// RetryOfGT applies the GT predicate on the "retry_of" field.
func RetryOfGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldRetryOf, v))
}

// RetryOfGTE applies the GTE predicate on the "retry_of" field.
func RetryOfGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldRetryOf, v))
}

// RetryOfLT applies the LT predicate on the "retry_of" field.
func RetryOfLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldRetryOf, v))
}

// RetryOfLTE applies the LTE predicate on the "retry_of" field.
func RetryOfLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldRetryOf, v))
}

// RetryOfContains applies the Contains predicate on the "retry_of" field.
func RetryOfContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldRetryOf, v))
}

// RetryOfHasPrefix applies the HasPrefix predicate on the "retry_of" field.
func RetryOfHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldRetryOf, v))
}

// RetryOfHasSuffix applies the HasSuffix predicate on the "retry_of" field.
func RetryOfHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldRetryOf, v))
}

// RetryOfIsNil applies the IsNil predicate on the "retry_of" field.
func RetryOfIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldRetryOf))
}

// RetryOfNotNil applies the NotNil predicate on the "retry_of" field.
func RetryOfNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldRetryOf))
}

// RetryOfEqualFold applies the EqualFold predicate on the "retry_of" field.
func RetryOfEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldRetryOf, v))
}

// RetryOfContainsFold applies the ContainsFold predicate on the "retry_of" field.
func RetryOfContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldRetryOf, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowRun) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowRun) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowRun) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.NotPredicates(p))
}
