// Code generated by ent, DO NOT EDIT.

package publication

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the publication type in the database.
	Label = "publication"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldItemID holds the string denoting the item_id field in the database.
	FieldItemID = "item_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldRevisionID holds the string denoting the revision_id field in the database.
	FieldRevisionID = "revision_id"
	// FieldPublishedBy holds the string denoting the published_by field in the database.
	FieldPublishedBy = "published_by"
	// FieldSnapshot holds the string denoting the snapshot field in the database.
	FieldSnapshot = "snapshot"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// EdgeRevision holds the string denoting the revision edge name in mutations.
	EdgeRevision = "revision"
	// Table holds the table name of the publication in the database.
	Table = "publications"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "publications"
	// ItemInverseTable is the table name for the Resource entity.
	// It exists in this package in order to avoid circular dependency with the "resource" package.
	ItemInverseTable = "resources"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "item_id"
	// RevisionTable is the table that holds the revision relation/edge.
	RevisionTable = "publications"
	// RevisionInverseTable is the table name for the ItemRevision entity.
	// It exists in this package in order to avoid circular dependency with the "itemrevision" package.
	RevisionInverseTable = "item_revisions"
	// RevisionColumn is the table column denoting the revision relation/edge.
	RevisionColumn = "revision_id"
)

// Columns holds all SQL columns for publication fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldItemID,
	FieldVersion,
	FieldAction,
	FieldRevisionID,
	FieldPublishedBy,
	FieldSnapshot,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	ItemIDValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
	// PublishedByValidator is a validator for the "published_by" field. It is called by the builders before save.
	PublishedByValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Action defines the type for the "action" enum field.
type Action string

// ActionPublish is the default value of the Action enum.
const DefaultAction = ActionPublish

// Action values.
const (
	ActionPublish   Action = "publish"
	ActionUnpublish Action = "unpublish"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionPublish, ActionUnpublish:
		return nil
	default:
		return fmt.Errorf("publication: invalid enum value for action field: %q", a)
	}
}

// OrderOption defines the ordering options for the Publication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByItemID orders the results by the item_id field.
func ByItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByRevisionID orders the results by the revision_id field.
func ByRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevisionID, opts...).ToFunc()
}

// ByPublishedBy orders the results by the published_by field.
func ByPublishedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedBy, opts...).ToFunc()
}

// ByItemField orders the results by item field.
func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
	}
}

// ByRevisionField orders the results by revision field.
func ByRevisionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRevisionStep(), sql.OrderByField(field, opts...))
	}
}
func newItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
	)
}
func newRevisionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RevisionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RevisionTable, RevisionColumn),
	)
}
