// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/businesskey"
	"papergo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BusinessKeyUpdate is the builder for updating BusinessKey entities.
type BusinessKeyUpdate struct {
	config
	hooks    []Hook
	mutation *BusinessKeyMutation
}

// Where appends a list predicates to the BusinessKeyUpdate builder.
func (_u *BusinessKeyUpdate) Where(ps ...predicate.BusinessKey) *BusinessKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the BusinessKeyMutation object of the builder.
func (_u *BusinessKeyUpdate) Mutation() *BusinessKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BusinessKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BusinessKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessKeyUpdate) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BusinessKey.item"`)
	}
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BusinessKey.container"`)
	}
	return nil
}

func (_u *BusinessKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businesskey.Table, businesskey.Columns, sqlgraph.NewFieldSpec(businesskey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businesskey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BusinessKeyUpdateOne is the builder for updating a single BusinessKey entity.
type BusinessKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BusinessKeyMutation
}

// Mutation returns the BusinessKeyMutation object of the builder.
func (_u *BusinessKeyUpdateOne) Mutation() *BusinessKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the BusinessKeyUpdate builder.
func (_u *BusinessKeyUpdateOne) Where(ps ...predicate.BusinessKey) *BusinessKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BusinessKeyUpdateOne) Select(field string, fields ...string) *BusinessKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BusinessKey entity.
func (_u *BusinessKeyUpdateOne) Save(ctx context.Context) (*BusinessKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessKeyUpdateOne) SaveX(ctx context.Context) *BusinessKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BusinessKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessKeyUpdateOne) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BusinessKey.item"`)
	}
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BusinessKey.container"`)
	}
	return nil
}

func (_u *BusinessKeyUpdateOne) sqlSave(ctx context.Context) (_node *BusinessKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businesskey.Table, businesskey.Columns, sqlgraph.NewFieldSpec(businesskey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BusinessKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businesskey.FieldID)
		for _, f := range fields {
			if !businesskey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != businesskey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &BusinessKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businesskey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
