// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"papergo/ent/businesskey"
	"papergo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BusinessKeyDelete is the builder for deleting a BusinessKey entity.
type BusinessKeyDelete struct {
	config
	hooks    []Hook
	mutation *BusinessKeyMutation
}

// Where appends a list predicates to the BusinessKeyDelete builder.
func (_d *BusinessKeyDelete) Where(ps ...predicate.BusinessKey) *BusinessKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BusinessKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BusinessKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(businesskey.Table, sqlgraph.NewFieldSpec(businesskey.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BusinessKeyDeleteOne is the builder for deleting a single BusinessKey entity.
type BusinessKeyDeleteOne struct {
	_d *BusinessKeyDelete
}

// Where appends a list predicates to the BusinessKeyDelete builder.
func (_d *BusinessKeyDeleteOne) Where(ps ...predicate.BusinessKey) *BusinessKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BusinessKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{businesskey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
