// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/fielddefinition"
	"papergo/ent/predicate"
	"papergo/internal/model"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// FieldDefinitionUpdate is the builder for updating FieldDefinition entities.
type FieldDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *FieldDefinitionMutation
}

// Where appends a list predicates to the FieldDefinitionUpdate builder.
func (_u *FieldDefinitionUpdate) Where(ps ...predicate.FieldDefinition) *FieldDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *FieldDefinitionUpdate) SetLabel(v string) *FieldDefinitionUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableLabel(v *string) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *FieldDefinitionUpdate) SetType(v fielddefinition.Type) *FieldDefinitionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableType(v *fielddefinition.Type) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetOptions sets the "options" field.
func (_u *FieldDefinitionUpdate) SetOptions(v model.FieldOptions) *FieldDefinitionUpdate {
	_u.mutation.SetOptions(v)
	return _u
}

// SetNillableOptions sets the "options" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableOptions(v *model.FieldOptions) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetOptions(*v)
	}
	return _u
}

// SetIndexed sets the "indexed" field.
func (_u *FieldDefinitionUpdate) SetIndexed(v bool) *FieldDefinitionUpdate {
	_u.mutation.SetIndexed(v)
	return _u
}

// SetNillableIndexed sets the "indexed" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableIndexed(v *bool) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetIndexed(*v)
	}
	return _u
}

// SetIndexStatus sets the "index_status" field.
func (_u *FieldDefinitionUpdate) SetIndexStatus(v fielddefinition.IndexStatus) *FieldDefinitionUpdate {
	_u.mutation.SetIndexStatus(v)
	return _u
}

// SetNillableIndexStatus sets the "index_status" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableIndexStatus(v *fielddefinition.IndexStatus) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetIndexStatus(*v)
	}
	return _u
}

// SetScale sets the "scale" field.
func (_u *FieldDefinitionUpdate) SetScale(v int) *FieldDefinitionUpdate {
	_u.mutation.ResetScale()
	_u.mutation.SetScale(v)
	return _u
}

// SetNillableScale sets the "scale" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableScale(v *int) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetScale(*v)
	}
	return _u
}

// AddScale adds value to the "scale" field.
func (_u *FieldDefinitionUpdate) AddScale(v int) *FieldDefinitionUpdate {
	_u.mutation.AddScale(v)
	return _u
}

// SetRequired sets the "required" field.
func (_u *FieldDefinitionUpdate) SetRequired(v bool) *FieldDefinitionUpdate {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableRequired(v *bool) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetChoices sets the "choices" field.
func (_u *FieldDefinitionUpdate) SetChoices(v []string) *FieldDefinitionUpdate {
	_u.mutation.SetChoices(v)
	return _u
}

// AppendChoices appends value to the "choices" field.
func (_u *FieldDefinitionUpdate) AppendChoices(v []string) *FieldDefinitionUpdate {
	_u.mutation.AppendChoices(v)
	return _u
}

// Mutation returns the FieldDefinitionMutation object of the builder.
func (_u *FieldDefinitionUpdate) Mutation() *FieldDefinitionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FieldDefinitionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FieldDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FieldDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FieldDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FieldDefinitionUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := fielddefinition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := fielddefinition.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IndexStatus(); ok {
		if err := fielddefinition.IndexStatusValidator(v); err != nil {
			return &ValidationError{Name: "index_status", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.index_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scale(); ok {
		if err := fielddefinition.ScaleValidator(v); err != nil {
			return &ValidationError{Name: "scale", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.scale": %w`, err)}
		}
	}
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FieldDefinition.container"`)
	}
	return nil
}

func (_u *FieldDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fielddefinition.Table, fielddefinition.Columns, sqlgraph.NewFieldSpec(fielddefinition.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(fielddefinition.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(fielddefinition.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(fielddefinition.FieldOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Indexed(); ok {
		_spec.SetField(fielddefinition.FieldIndexed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IndexStatus(); ok {
		_spec.SetField(fielddefinition.FieldIndexStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Scale(); ok {
		_spec.SetField(fielddefinition.FieldScale, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScale(); ok {
		_spec.AddField(fielddefinition.FieldScale, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(fielddefinition.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Choices(); ok {
		_spec.SetField(fielddefinition.FieldChoices, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChoices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, fielddefinition.FieldChoices, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fielddefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FieldDefinitionUpdateOne is the builder for updating a single FieldDefinition entity.
type FieldDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FieldDefinitionMutation
}

// SetLabel sets the "label" field.
func (_u *FieldDefinitionUpdateOne) SetLabel(v string) *FieldDefinitionUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableLabel(v *string) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *FieldDefinitionUpdateOne) SetType(v fielddefinition.Type) *FieldDefinitionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableType(v *fielddefinition.Type) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetOptions sets the "options" field.
func (_u *FieldDefinitionUpdateOne) SetOptions(v model.FieldOptions) *FieldDefinitionUpdateOne {
	_u.mutation.SetOptions(v)
	return _u
}

// SetNillableOptions sets the "options" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableOptions(v *model.FieldOptions) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetOptions(*v)
	}
	return _u
}

// SetIndexed sets the "indexed" field.
func (_u *FieldDefinitionUpdateOne) SetIndexed(v bool) *FieldDefinitionUpdateOne {
	_u.mutation.SetIndexed(v)
	return _u
}

// SetNillableIndexed sets the "indexed" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableIndexed(v *bool) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetIndexed(*v)
	}
	return _u
}

// SetIndexStatus sets the "index_status" field.
func (_u *FieldDefinitionUpdateOne) SetIndexStatus(v fielddefinition.IndexStatus) *FieldDefinitionUpdateOne {
	_u.mutation.SetIndexStatus(v)
	return _u
}

// SetNillableIndexStatus sets the "index_status" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableIndexStatus(v *fielddefinition.IndexStatus) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetIndexStatus(*v)
	}
	return _u
}

// SetScale sets the "scale" field.
func (_u *FieldDefinitionUpdateOne) SetScale(v int) *FieldDefinitionUpdateOne {
	_u.mutation.ResetScale()
	_u.mutation.SetScale(v)
	return _u
}

// SetNillableScale sets the "scale" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableScale(v *int) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetScale(*v)
	}
	return _u
}

// AddScale adds value to the "scale" field.
func (_u *FieldDefinitionUpdateOne) AddScale(v int) *FieldDefinitionUpdateOne {
	_u.mutation.AddScale(v)
	return _u
}

// SetRequired sets the "required" field.
func (_u *FieldDefinitionUpdateOne) SetRequired(v bool) *FieldDefinitionUpdateOne {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableRequired(v *bool) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetChoices sets the "choices" field.
func (_u *FieldDefinitionUpdateOne) SetChoices(v []string) *FieldDefinitionUpdateOne {
	_u.mutation.SetChoices(v)
	return _u
}

// AppendChoices appends value to the "choices" field.
func (_u *FieldDefinitionUpdateOne) AppendChoices(v []string) *FieldDefinitionUpdateOne {
	_u.mutation.AppendChoices(v)
	return _u
}

// Mutation returns the FieldDefinitionMutation object of the builder.
func (_u *FieldDefinitionUpdateOne) Mutation() *FieldDefinitionMutation {
	return _u.mutation
}

// Where appends a list predicates to the FieldDefinitionUpdate builder.
func (_u *FieldDefinitionUpdateOne) Where(ps ...predicate.FieldDefinition) *FieldDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FieldDefinitionUpdateOne) Select(field string, fields ...string) *FieldDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FieldDefinition entity.
func (_u *FieldDefinitionUpdateOne) Save(ctx context.Context) (*FieldDefinition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FieldDefinitionUpdateOne) SaveX(ctx context.Context) *FieldDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FieldDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FieldDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FieldDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := fielddefinition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := fielddefinition.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IndexStatus(); ok {
		if err := fielddefinition.IndexStatusValidator(v); err != nil {
			return &ValidationError{Name: "index_status", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.index_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scale(); ok {
		if err := fielddefinition.ScaleValidator(v); err != nil {
			return &ValidationError{Name: "scale", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.scale": %w`, err)}
		}
	}
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FieldDefinition.container"`)
	}
	return nil
}

func (_u *FieldDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *FieldDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fielddefinition.Table, fielddefinition.Columns, sqlgraph.NewFieldSpec(fielddefinition.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FieldDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fielddefinition.FieldID)
		for _, f := range fields {
			if !fielddefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fielddefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(fielddefinition.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(fielddefinition.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(fielddefinition.FieldOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Indexed(); ok {
		_spec.SetField(fielddefinition.FieldIndexed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IndexStatus(); ok {
		_spec.SetField(fielddefinition.FieldIndexStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Scale(); ok {
		_spec.SetField(fielddefinition.FieldScale, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScale(); ok {
		_spec.AddField(fielddefinition.FieldScale, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(fielddefinition.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Choices(); ok {
		_spec.SetField(fielddefinition.FieldChoices, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChoices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, fielddefinition.FieldChoices, value)
		})
	}
	_node = &FieldDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fielddefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
