// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"papergo/ent/fieldvalue"
	"papergo/ent/itemsurface"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FieldValue is the model entity for the FieldValue schema.
type FieldValue struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// SurfaceID holds the value of the "surface_id" field.
	SurfaceID string `json:"surface_id,omitempty"`
	// ContainerID holds the value of the "container_id" field.
	ContainerID string `json:"container_id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID string `json:"item_id,omitempty"`
	// Surface holds the value of the "surface" field.
	Surface fieldvalue.Surface `json:"surface,omitempty"`
	// FieldKey holds the value of the "field_key" field.
	FieldKey string `json:"field_key,omitempty"`
	// FieldType holds the value of the "field_type" field.
	FieldType fieldvalue.FieldType `json:"field_type,omitempty"`
	// Ordinal holds the value of the "ordinal" field.
	Ordinal int `json:"ordinal,omitempty"`
	// Scale holds the value of the "scale" field.
	Scale int `json:"scale,omitempty"`
	// ValueText holds the value of the "value_text" field.
	ValueText *string `json:"value_text,omitempty"`
	// ValueInteger holds the value of the "value_integer" field.
	ValueInteger *int64 `json:"value_integer,omitempty"`
	// ValueNumber holds the value of the "value_number" field.
	ValueNumber *float64 `json:"value_number,omitempty"`
	// ValueBoolean holds the value of the "value_boolean" field.
	ValueBoolean *bool `json:"value_boolean,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FieldValueQuery when eager-loading is set.
	Edges        FieldValueEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FieldValueEdges holds the relations/edges for other nodes in the graph.
type FieldValueEdges struct {
	// ItemSurface holds the value of the item_surface edge.
	ItemSurface *ItemSurface `json:"item_surface,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemSurfaceOrErr returns the ItemSurface value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FieldValueEdges) ItemSurfaceOrErr() (*ItemSurface, error) {
	if e.ItemSurface != nil {
		return e.ItemSurface, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: itemsurface.Label}
	}
	return nil, &NotLoadedError{edge: "item_surface"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FieldValue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fieldvalue.FieldValueBoolean:
			values[i] = new(sql.NullBool)
		case fieldvalue.FieldValueNumber:
			values[i] = new(sql.NullFloat64)
		case fieldvalue.FieldOrdinal, fieldvalue.FieldScale, fieldvalue.FieldValueInteger:
			values[i] = new(sql.NullInt64)
		case fieldvalue.FieldID, fieldvalue.FieldSurfaceID, fieldvalue.FieldContainerID, fieldvalue.FieldItemID, fieldvalue.FieldSurface, fieldvalue.FieldFieldKey, fieldvalue.FieldFieldType, fieldvalue.FieldValueText:
			values[i] = new(sql.NullString)
		case fieldvalue.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FieldValue fields.
func (_m *FieldValue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fieldvalue.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fieldvalue.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fieldvalue.FieldSurfaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field surface_id", values[i])
			} else if value.Valid {
				_m.SurfaceID = value.String
			}
		case fieldvalue.FieldContainerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container_id", values[i])
			} else if value.Valid {
				_m.ContainerID = value.String
			}
		case fieldvalue.FieldItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = value.String
			}
		case fieldvalue.FieldSurface:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field surface", values[i])
			} else if value.Valid {
				_m.Surface = fieldvalue.Surface(value.String)
			}
		case fieldvalue.FieldFieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_key", values[i])
			} else if value.Valid {
				_m.FieldKey = value.String
			}
		case fieldvalue.FieldFieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_type", values[i])
			} else if value.Valid {
				_m.FieldType = fieldvalue.FieldType(value.String)
			}
		case fieldvalue.FieldOrdinal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ordinal", values[i])
			} else if value.Valid {
				_m.Ordinal = int(value.Int64)
			}
		case fieldvalue.FieldScale:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scale", values[i])
			} else if value.Valid {
				_m.Scale = int(value.Int64)
			}
		case fieldvalue.FieldValueText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value_text", values[i])
			} else if value.Valid {
				_m.ValueText = new(string)
				*_m.ValueText = value.String
			}
		case fieldvalue.FieldValueInteger:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value_integer", values[i])
			} else if value.Valid {
				_m.ValueInteger = new(int64)
				*_m.ValueInteger = value.Int64
			}
		case fieldvalue.FieldValueNumber:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value_number", values[i])
			} else if value.Valid {
				_m.ValueNumber = new(float64)
				*_m.ValueNumber = value.Float64
			}
		case fieldvalue.FieldValueBoolean:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field value_boolean", values[i])
			} else if value.Valid {
				_m.ValueBoolean = new(bool)
				*_m.ValueBoolean = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FieldValue.
// This includes values selected through modifiers, order, etc.
func (_m *FieldValue) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItemSurface queries the "item_surface" edge of the FieldValue entity.
func (_m *FieldValue) QueryItemSurface() *ItemSurfaceQuery {
	return NewFieldValueClient(_m.config).QueryItemSurface(_m)
}

// Update returns a builder for updating this FieldValue.
// Note that you need to call FieldValue.Unwrap() before calling this method if this FieldValue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FieldValue) Update() *FieldValueUpdateOne {
	return NewFieldValueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FieldValue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FieldValue) Unwrap() *FieldValue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FieldValue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FieldValue) String() string {
	var builder strings.Builder
	builder.WriteString("FieldValue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("surface_id=")
	builder.WriteString(_m.SurfaceID)
	builder.WriteString(", ")
	builder.WriteString("container_id=")
	builder.WriteString(_m.ContainerID)
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(_m.ItemID)
	builder.WriteString(", ")
	builder.WriteString("surface=")
	builder.WriteString(fmt.Sprintf("%v", _m.Surface))
	builder.WriteString(", ")
	builder.WriteString("field_key=")
	builder.WriteString(_m.FieldKey)
	builder.WriteString(", ")
	builder.WriteString("field_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.FieldType))
	builder.WriteString(", ")
	builder.WriteString("ordinal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ordinal))
	builder.WriteString(", ")
	builder.WriteString("scale=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scale))
	builder.WriteString(", ")
	if v := _m.ValueText; v != nil {
		builder.WriteString("value_text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ValueInteger; v != nil {
		builder.WriteString("value_integer=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValueNumber; v != nil {
		builder.WriteString("value_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValueBoolean; v != nil {
		builder.WriteString("value_boolean=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// FieldValues is a parsable slice of FieldValue.
type FieldValues []*FieldValue
