// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/grant"
	"papergo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GrantUpdate is the builder for updating Grant entities.
type GrantUpdate struct {
	config
	hooks    []Hook
	mutation *GrantMutation
}

// Where appends a list predicates to the GrantUpdate builder.
func (_u *GrantUpdate) Where(ps ...predicate.Grant) *GrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *GrantUpdate) SetSubject(v string) *GrantUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *GrantUpdate) SetNillableSubject(v *string) *GrantUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *GrantUpdate) SetAction(v grant.Action) *GrantUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *GrantUpdate) SetNillableAction(v *grant.Action) *GrantUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetEffect sets the "effect" field.
func (_u *GrantUpdate) SetEffect(v grant.Effect) *GrantUpdate {
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *GrantUpdate) SetNillableEffect(v *grant.Effect) *GrantUpdate {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// Mutation returns the GrantMutation object of the builder.
func (_u *GrantUpdate) Mutation() *GrantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrantUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := grant.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Grant.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := grant.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Grant.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Effect(); ok {
		if err := grant.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "Grant.effect": %w`, err)}
		}
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Grant.resource"`)
	}
	return nil
}

func (_u *GrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grant.Table, grant.Columns, sqlgraph.NewFieldSpec(grant.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(grant.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(grant.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(grant.FieldEffect, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GrantUpdateOne is the builder for updating a single Grant entity.
type GrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GrantMutation
}

// SetSubject sets the "subject" field.
func (_u *GrantUpdateOne) SetSubject(v string) *GrantUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *GrantUpdateOne) SetNillableSubject(v *string) *GrantUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *GrantUpdateOne) SetAction(v grant.Action) *GrantUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *GrantUpdateOne) SetNillableAction(v *grant.Action) *GrantUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetEffect sets the "effect" field.
func (_u *GrantUpdateOne) SetEffect(v grant.Effect) *GrantUpdateOne {
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *GrantUpdateOne) SetNillableEffect(v *grant.Effect) *GrantUpdateOne {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// Mutation returns the GrantMutation object of the builder.
func (_u *GrantUpdateOne) Mutation() *GrantMutation {
	return _u.mutation
}

// Where appends a list predicates to the GrantUpdate builder.
func (_u *GrantUpdateOne) Where(ps ...predicate.Grant) *GrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GrantUpdateOne) Select(field string, fields ...string) *GrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Grant entity.
func (_u *GrantUpdateOne) Save(ctx context.Context) (*Grant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrantUpdateOne) SaveX(ctx context.Context) *Grant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrantUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := grant.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Grant.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := grant.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Grant.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Effect(); ok {
		if err := grant.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "Grant.effect": %w`, err)}
		}
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Grant.resource"`)
	}
	return nil
}

func (_u *GrantUpdateOne) sqlSave(ctx context.Context) (_node *Grant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grant.Table, grant.Columns, sqlgraph.NewFieldSpec(grant.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Grant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grant.FieldID)
		for _, f := range fields {
			if !grant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(grant.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(grant.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(grant.FieldEffect, field.TypeEnum, value)
	}
	_node = &Grant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
