// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"papergo/ent/listview"
	"papergo/ent/resource"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ListViewCreate is the builder for creating a ListView entity.
type ListViewCreate struct {
	config
	mutation *ListViewMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ListViewCreate) SetCreatedAt(v time.Time) *ListViewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ListViewCreate) SetNillableCreatedAt(v *time.Time) *ListViewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetContainerID sets the "container_id" field.
func (_c *ListViewCreate) SetContainerID(v string) *ListViewCreate {
	_c.mutation.SetContainerID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ListViewCreate) SetName(v string) *ListViewCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetColumns sets the "columns" field.
func (_c *ListViewCreate) SetColumns(v []string) *ListViewCreate {
	_c.mutation.SetColumns(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *ListViewCreate) SetQuery(v jsontext.Value) *ListViewCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetLayout sets the "layout" field.
func (_c *ListViewCreate) SetLayout(v string) *ListViewCreate {
	_c.mutation.SetLayout(v)
	return _c
}

// SetNillableLayout sets the "layout" field if the given value is not nil.
func (_c *ListViewCreate) SetNillableLayout(v *string) *ListViewCreate {
	if v != nil {
		_c.SetLayout(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ListViewCreate) SetIsDefault(v bool) *ListViewCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ListViewCreate) SetNillableIsDefault(v *bool) *ListViewCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ListViewCreate) SetVersion(v int) *ListViewCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ListViewCreate) SetNillableVersion(v *int) *ListViewCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ListViewCreate) SetUpdatedAt(v time.Time) *ListViewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ListViewCreate) SetNillableUpdatedAt(v *time.Time) *ListViewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ListViewCreate) SetID(v string) *ListViewCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ListViewCreate) SetNillableID(v *string) *ListViewCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetContainer sets the "container" edge to the Resource entity.
func (_c *ListViewCreate) SetContainer(v *Resource) *ListViewCreate {
	return _c.SetContainerID(v.ID)
}

// Mutation returns the ListViewMutation object of the builder.
func (_c *ListViewCreate) Mutation() *ListViewMutation {
	return _c.mutation
}

// Save creates the ListView in the database.
func (_c *ListViewCreate) Save(ctx context.Context) (*ListView, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListViewCreate) SaveX(ctx context.Context) *ListView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListViewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListViewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListViewCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := listview.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Columns(); !ok {
		v := listview.DefaultColumns
		_c.mutation.SetColumns(v)
	}
	if _, ok := _c.mutation.Layout(); !ok {
		v := listview.DefaultLayout
		_c.mutation.SetLayout(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := listview.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := listview.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := listview.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := listview.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListViewCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ListView.created_at"`)}
	}
	if _, ok := _c.mutation.ContainerID(); !ok {
		return &ValidationError{Name: "container_id", err: errors.New(`ent: missing required field "ListView.container_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ListView.name"`)}
	}
	if _, ok := _c.mutation.Columns(); !ok {
		return &ValidationError{Name: "columns", err: errors.New(`ent: missing required field "ListView.columns"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "ListView.query"`)}
	}
	if _, ok := _c.mutation.Layout(); !ok {
		return &ValidationError{Name: "layout", err: errors.New(`ent: missing required field "ListView.layout"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ListView.is_default"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ListView.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := listview.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ListView.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ListView.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := listview.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ListView.id": %w`, err)}
		}
	}
	if len(_c.mutation.ContainerIDs()) == 0 {
		return &ValidationError{Name: "container", err: errors.New(`ent: missing required edge "ListView.container"`)}
	}
	return nil
}

func (_c *ListViewCreate) sqlSave(ctx context.Context) (*ListView, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ListView.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListViewCreate) createSpec() (*ListView, *sqlgraph.CreateSpec) {
	var (
		_node = &ListView{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listview.Table, sqlgraph.NewFieldSpec(listview.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(listview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(listview.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Columns(); ok {
		_spec.SetField(listview.FieldColumns, field.TypeJSON, value)
		_node.Columns = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(listview.FieldQuery, field.TypeJSON, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.Layout(); ok {
		_spec.SetField(listview.FieldLayout, field.TypeString, value)
		_node.Layout = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(listview.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(listview.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(listview.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   listview.ContainerTable,
			Columns: []string{listview.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContainerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ListViewCreateBulk is the builder for creating many ListView entities in bulk.
type ListViewCreateBulk struct {
	config
	err      error
	builders []*ListViewCreate
}

// Save creates the ListView entities in the database.
func (_c *ListViewCreateBulk) Save(ctx context.Context) ([]*ListView, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ListView, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListViewCreateBulk) SaveX(ctx context.Context) []*ListView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListViewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListViewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
