// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/operation"
	"papergo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OperationUpdate is the builder for updating Operation entities.
type OperationUpdate struct {
	config
	hooks    []Hook
	mutation *OperationMutation
}

// Where appends a list predicates to the OperationUpdate builder.
func (_u *OperationUpdate) Where(ps ...predicate.Operation) *OperationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OperationUpdate) SetStatus(v operation.Status) *OperationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OperationUpdate) SetNillableStatus(v *operation.Status) *OperationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSurface sets the "surface" field.
func (_u *OperationUpdate) SetSurface(v operation.Surface) *OperationUpdate {
	_u.mutation.SetSurface(v)
	return _u
}

// SetNillableSurface sets the "surface" field if the given value is not nil.
func (_u *OperationUpdate) SetNillableSurface(v *operation.Surface) *OperationUpdate {
	if v != nil {
		_u.SetSurface(*v)
	}
	return _u
}

// SetAfterItemID sets the "after_item_id" field.
func (_u *OperationUpdate) SetAfterItemID(v string) *OperationUpdate {
	_u.mutation.SetAfterItemID(v)
	return _u
}

// SetNillableAfterItemID sets the "after_item_id" field if the given value is not nil.
func (_u *OperationUpdate) SetNillableAfterItemID(v *string) *OperationUpdate {
	if v != nil {
		_u.SetAfterItemID(*v)
	}
	return _u
}

// SetProcessed sets the "processed" field.
func (_u *OperationUpdate) SetProcessed(v int) *OperationUpdate {
	_u.mutation.ResetProcessed()
	_u.mutation.SetProcessed(v)
	return _u
}

// SetNillableProcessed sets the "processed" field if the given value is not nil.
func (_u *OperationUpdate) SetNillableProcessed(v *int) *OperationUpdate {
	if v != nil {
		_u.SetProcessed(*v)
	}
	return _u
}

// AddProcessed adds value to the "processed" field.
func (_u *OperationUpdate) AddProcessed(v int) *OperationUpdate {
	_u.mutation.AddProcessed(v)
	return _u
}

// SetError sets the "error" field.
func (_u *OperationUpdate) SetError(v string) *OperationUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *OperationUpdate) SetNillableError(v *string) *OperationUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OperationUpdate) SetUpdatedAt(v time.Time) *OperationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OperationMutation object of the builder.
func (_u *OperationUpdate) Mutation() *OperationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OperationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OperationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OperationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := operation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OperationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := operation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Operation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Surface(); ok {
		if err := operation.SurfaceValidator(v); err != nil {
			return &ValidationError{Name: "surface", err: fmt.Errorf(`ent: validator failed for field "Operation.surface": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Processed(); ok {
		if err := operation.ProcessedValidator(v); err != nil {
			return &ValidationError{Name: "processed", err: fmt.Errorf(`ent: validator failed for field "Operation.processed": %w`, err)}
		}
	}
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Operation.container"`)
	}
	return nil
}

func (_u *OperationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(operation.Table, operation.Columns, sqlgraph.NewFieldSpec(operation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(operation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Surface(); ok {
		_spec.SetField(operation.FieldSurface, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AfterItemID(); ok {
		_spec.SetField(operation.FieldAfterItemID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Processed(); ok {
		_spec.SetField(operation.FieldProcessed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessed(); ok {
		_spec.AddField(operation.FieldProcessed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(operation.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(operation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OperationUpdateOne is the builder for updating a single Operation entity.
type OperationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OperationMutation
}

// SetStatus sets the "status" field.
func (_u *OperationUpdateOne) SetStatus(v operation.Status) *OperationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OperationUpdateOne) SetNillableStatus(v *operation.Status) *OperationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSurface sets the "surface" field.
func (_u *OperationUpdateOne) SetSurface(v operation.Surface) *OperationUpdateOne {
	_u.mutation.SetSurface(v)
	return _u
}

// SetNillableSurface sets the "surface" field if the given value is not nil.
func (_u *OperationUpdateOne) SetNillableSurface(v *operation.Surface) *OperationUpdateOne {
	if v != nil {
		_u.SetSurface(*v)
	}
	return _u
}

// SetAfterItemID sets the "after_item_id" field.
func (_u *OperationUpdateOne) SetAfterItemID(v string) *OperationUpdateOne {
	_u.mutation.SetAfterItemID(v)
	return _u
}

// SetNillableAfterItemID sets the "after_item_id" field if the given value is not nil.
func (_u *OperationUpdateOne) SetNillableAfterItemID(v *string) *OperationUpdateOne {
	if v != nil {
		_u.SetAfterItemID(*v)
	}
	return _u
}

// SetProcessed sets the "processed" field.
func (_u *OperationUpdateOne) SetProcessed(v int) *OperationUpdateOne {
	_u.mutation.ResetProcessed()
	_u.mutation.SetProcessed(v)
	return _u
}

// SetNillableProcessed sets the "processed" field if the given value is not nil.
func (_u *OperationUpdateOne) SetNillableProcessed(v *int) *OperationUpdateOne {
	if v != nil {
		_u.SetProcessed(*v)
	}
	return _u
}

// AddProcessed adds value to the "processed" field.
func (_u *OperationUpdateOne) AddProcessed(v int) *OperationUpdateOne {
	_u.mutation.AddProcessed(v)
	return _u
}

// SetError sets the "error" field.
func (_u *OperationUpdateOne) SetError(v string) *OperationUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *OperationUpdateOne) SetNillableError(v *string) *OperationUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OperationUpdateOne) SetUpdatedAt(v time.Time) *OperationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OperationMutation object of the builder.
func (_u *OperationUpdateOne) Mutation() *OperationMutation {
	return _u.mutation
}

// Where appends a list predicates to the OperationUpdate builder.
func (_u *OperationUpdateOne) Where(ps ...predicate.Operation) *OperationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OperationUpdateOne) Select(field string, fields ...string) *OperationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Operation entity.
func (_u *OperationUpdateOne) Save(ctx context.Context) (*Operation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperationUpdateOne) SaveX(ctx context.Context) *Operation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OperationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OperationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := operation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OperationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := operation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Operation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Surface(); ok {
		if err := operation.SurfaceValidator(v); err != nil {
			return &ValidationError{Name: "surface", err: fmt.Errorf(`ent: validator failed for field "Operation.surface": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Processed(); ok {
		if err := operation.ProcessedValidator(v); err != nil {
			return &ValidationError{Name: "processed", err: fmt.Errorf(`ent: validator failed for field "Operation.processed": %w`, err)}
		}
	}
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Operation.container"`)
	}
	return nil
}

func (_u *OperationUpdateOne) sqlSave(ctx context.Context) (_node *Operation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(operation.Table, operation.Columns, sqlgraph.NewFieldSpec(operation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Operation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operation.FieldID)
		for _, f := range fields {
			if !operation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != operation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(operation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Surface(); ok {
		_spec.SetField(operation.FieldSurface, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AfterItemID(); ok {
		_spec.SetField(operation.FieldAfterItemID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Processed(); ok {
		_spec.SetField(operation.FieldProcessed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessed(); ok {
		_spec.AddField(operation.FieldProcessed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(operation.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(operation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Operation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
