// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"papergo/ent/itemrevision"
	"papergo/ent/publication"
	"papergo/ent/resource"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Publication is the model entity for the Publication schema.
type Publication struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID string `json:"item_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Action holds the value of the "action" field.
	Action publication.Action `json:"action,omitempty"`
	// RevisionID holds the value of the "revision_id" field.
	RevisionID *string `json:"revision_id,omitempty"`
	// PublishedBy holds the value of the "published_by" field.
	PublishedBy string `json:"published_by,omitempty"`
	// Snapshot holds the value of the "snapshot" field.
	Snapshot jsontext.Value `json:"snapshot,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PublicationQuery when eager-loading is set.
	Edges        PublicationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PublicationEdges holds the relations/edges for other nodes in the graph.
type PublicationEdges struct {
	// Item holds the value of the item edge.
	Item *Resource `json:"item,omitempty"`
	// Revision holds the value of the revision edge.
	Revision *ItemRevision `json:"revision,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PublicationEdges) ItemOrErr() (*Resource, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: resource.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// RevisionOrErr returns the Revision value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PublicationEdges) RevisionOrErr() (*ItemRevision, error) {
	if e.Revision != nil {
		return e.Revision, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: itemrevision.Label}
	}
	return nil, &NotLoadedError{edge: "revision"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Publication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case publication.FieldSnapshot:
			values[i] = new([]byte)
		case publication.FieldVersion:
			values[i] = new(sql.NullInt64)
		case publication.FieldID, publication.FieldItemID, publication.FieldAction, publication.FieldRevisionID, publication.FieldPublishedBy:
			values[i] = new(sql.NullString)
		case publication.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Publication fields.
func (_m *Publication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case publication.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case publication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case publication.FieldItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = value.String
			}
		case publication.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case publication.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = publication.Action(value.String)
			}
		case publication.FieldRevisionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revision_id", values[i])
			} else if value.Valid {
				_m.RevisionID = new(string)
				*_m.RevisionID = value.String
			}
		case publication.FieldPublishedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field published_by", values[i])
			} else if value.Valid {
				_m.PublishedBy = value.String
			}
		case publication.FieldSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Snapshot); err != nil {
					return fmt.Errorf("unmarshal field snapshot: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Publication.
// This includes values selected through modifiers, order, etc.
func (_m *Publication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the Publication entity.
func (_m *Publication) QueryItem() *ResourceQuery {
	return NewPublicationClient(_m.config).QueryItem(_m)
}

// QueryRevision queries the "revision" edge of the Publication entity.
func (_m *Publication) QueryRevision() *ItemRevisionQuery {
	return NewPublicationClient(_m.config).QueryRevision(_m)
}

// Update returns a builder for updating this Publication.
// Note that you need to call Publication.Unwrap() before calling this method if this Publication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Publication) Update() *PublicationUpdateOne {
	return NewPublicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Publication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Publication) Unwrap() *Publication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Publication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Publication) String() string {
	var builder strings.Builder
	builder.WriteString("Publication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(_m.ItemID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	if v := _m.RevisionID; v != nil {
		builder.WriteString("revision_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("published_by=")
	builder.WriteString(_m.PublishedBy)
	builder.WriteString(", ")
	builder.WriteString("snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.Snapshot))
	builder.WriteByte(')')
	return builder.String()
}

// Publications is a parsable slice of Publication.
type Publications []*Publication
