// Code generated by ent, DO NOT EDIT.

package ent

import (
	"papergo/ent/auditevent"
	"papergo/ent/blob"
	"papergo/ent/businesskey"
	"papergo/ent/contenttype"
	"papergo/ent/domainevent"
	"papergo/ent/fielddefinition"
	"papergo/ent/fieldvalue"
	"papergo/ent/grant"
	"papergo/ent/itemrevision"
	"papergo/ent/itemsurface"
	"papergo/ent/listview"
	"papergo/ent/publication"
	"papergo/ent/relationship"
	"papergo/ent/relationshiptype"
	"papergo/ent/resource"
	"papergo/ent/schema"
	"papergo/ent/schemarevision"
	"papergo/ent/schematemplate"
	"papergo/ent/smartfolder"
	"papergo/ent/term"
	"papergo/ent/termgroup"
	"papergo/ent/termset"
	"papergo/ent/webdavcredential"
	"papergo/ent/workflow"
	"papergo/ent/workflowrun"
	"papergo/ent/workflowrunitem"
	"papergo/ent/workflowtrigger"
	"papergo/ent/workflowversion"
	"papergo/internal/model"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditeventMixin := schema.AuditEvent{}.Mixin()
	auditeventMixinFields0 := auditeventMixin[0].Fields()
	_ = auditeventMixinFields0
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescCreatedAt is the schema descriptor for created_at field.
	auditeventDescCreatedAt := auditeventMixinFields0[1].Descriptor()
	// auditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditevent.DefaultCreatedAt = auditeventDescCreatedAt.Default.(func() time.Time)
	// auditeventDescWorkspaceID is the schema descriptor for workspace_id field.
	auditeventDescWorkspaceID := auditeventFields[0].Descriptor()
	// auditevent.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	auditevent.WorkspaceIDValidator = auditeventDescWorkspaceID.Validators[0].(func(string) error)
	// auditeventDescResourceID is the schema descriptor for resource_id field.
	auditeventDescResourceID := auditeventFields[1].Descriptor()
	// auditevent.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	auditevent.ResourceIDValidator = auditeventDescResourceID.Validators[0].(func(string) error)
	// auditeventDescSubject is the schema descriptor for subject field.
	auditeventDescSubject := auditeventFields[2].Descriptor()
	// auditevent.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	auditevent.SubjectValidator = auditeventDescSubject.Validators[0].(func(string) error)
	// auditeventDescAction is the schema descriptor for action field.
	auditeventDescAction := auditeventFields[3].Descriptor()
	// auditevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditevent.ActionValidator = auditeventDescAction.Validators[0].(func(string) error)
	// auditeventDescDetails is the schema descriptor for details field.
	auditeventDescDetails := auditeventFields[4].Descriptor()
	// auditevent.DefaultDetails holds the default value on creation for the details field.
	auditevent.DefaultDetails = auditeventDescDetails.Default.(map[string]interface{})
	// auditeventDescID is the schema descriptor for id field.
	auditeventDescID := auditeventMixinFields0[0].Descriptor()
	// auditevent.DefaultID holds the default value on creation for the id field.
	auditevent.DefaultID = auditeventDescID.Default.(func() string)
	// auditevent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auditevent.IDValidator = auditeventDescID.Validators[0].(func(string) error)
	blobMixin := schema.Blob{}.Mixin()
	blobMixinFields0 := blobMixin[0].Fields()
	_ = blobMixinFields0
	blobFields := schema.Blob{}.Fields()
	_ = blobFields
	// blobDescCreatedAt is the schema descriptor for created_at field.
	blobDescCreatedAt := blobMixinFields0[1].Descriptor()
	// blob.DefaultCreatedAt holds the default value on creation for the created_at field.
	blob.DefaultCreatedAt = blobDescCreatedAt.Default.(func() time.Time)
	// blobDescItemID is the schema descriptor for item_id field.
	blobDescItemID := blobFields[0].Descriptor()
	// blob.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	blob.ItemIDValidator = func() func(string) error {
		validators := blobDescItemID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(item string) error {
			for _, fn := range fns {
				if err := fn(item); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// blobDescVersion is the schema descriptor for version field.
	blobDescVersion := blobFields[1].Descriptor()
	// blob.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	blob.VersionValidator = blobDescVersion.Validators[0].(func(int) error)
	// blobDescObjectKey is the schema descriptor for object_key field.
	blobDescObjectKey := blobFields[2].Descriptor()
	// blob.ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	blob.ObjectKeyValidator = blobDescObjectKey.Validators[0].(func(string) error)
	// blobDescFilename is the schema descriptor for filename field.
	blobDescFilename := blobFields[3].Descriptor()
	// blob.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	blob.FilenameValidator = func() func(string) error {
		validators := blobDescFilename.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(filename string) error {
			for _, fn := range fns {
				if err := fn(filename); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// blobDescContentType is the schema descriptor for content_type field.
	blobDescContentType := blobFields[4].Descriptor()
	// blob.ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	blob.ContentTypeValidator = func() func(string) error {
		validators := blobDescContentType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content_type string) error {
			for _, fn := range fns {
				if err := fn(content_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// blobDescSize is the schema descriptor for size field.
	blobDescSize := blobFields[5].Descriptor()
	// blob.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	blob.SizeValidator = blobDescSize.Validators[0].(func(int64) error)
	// blobDescSha256 is the schema descriptor for sha256 field.
	blobDescSha256 := blobFields[6].Descriptor()
	// blob.Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	blob.Sha256Validator = func() func(string) error {
		validators := blobDescSha256.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sha256 string) error {
			for _, fn := range fns {
				if err := fn(sha256); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// blobDescID is the schema descriptor for id field.
	blobDescID := blobMixinFields0[0].Descriptor()
	// blob.DefaultID holds the default value on creation for the id field.
	blob.DefaultID = blobDescID.Default.(func() string)
	// blob.IDValidator is a validator for the "id" field. It is called by the builders before save.
	blob.IDValidator = blobDescID.Validators[0].(func(string) error)
	businesskeyMixin := schema.BusinessKey{}.Mixin()
	businesskeyMixinFields0 := businesskeyMixin[0].Fields()
	_ = businesskeyMixinFields0
	businesskeyFields := schema.BusinessKey{}.Fields()
	_ = businesskeyFields
	// businesskeyDescCreatedAt is the schema descriptor for created_at field.
	businesskeyDescCreatedAt := businesskeyMixinFields0[1].Descriptor()
	// businesskey.DefaultCreatedAt holds the default value on creation for the created_at field.
	businesskey.DefaultCreatedAt = businesskeyDescCreatedAt.Default.(func() time.Time)
	// businesskeyDescID is the schema descriptor for id field.
	businesskeyDescID := businesskeyMixinFields0[0].Descriptor()
	// businesskey.DefaultID holds the default value on creation for the id field.
	businesskey.DefaultID = businesskeyDescID.Default.(func() string)
	// businesskey.IDValidator is a validator for the "id" field. It is called by the builders before save.
	businesskey.IDValidator = businesskeyDescID.Validators[0].(func(string) error)
	contenttypeMixin := schema.ContentType{}.Mixin()
	contenttypeMixinFields0 := contenttypeMixin[0].Fields()
	_ = contenttypeMixinFields0
	contenttypeFields := schema.ContentType{}.Fields()
	_ = contenttypeFields
	// contenttypeDescCreatedAt is the schema descriptor for created_at field.
	contenttypeDescCreatedAt := contenttypeMixinFields0[1].Descriptor()
	// contenttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	contenttype.DefaultCreatedAt = contenttypeDescCreatedAt.Default.(func() time.Time)
	// contenttypeDescKey is the schema descriptor for key field.
	contenttypeDescKey := contenttypeFields[1].Descriptor()
	// contenttype.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	contenttype.KeyValidator = contenttypeDescKey.Validators[0].(func(string) error)
	// contenttypeDescName is the schema descriptor for name field.
	contenttypeDescName := contenttypeFields[2].Descriptor()
	// contenttype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	contenttype.NameValidator = func() func(string) error {
		validators := contenttypeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// contenttypeDescFieldKeys is the schema descriptor for field_keys field.
	contenttypeDescFieldKeys := contenttypeFields[3].Descriptor()
	// contenttype.DefaultFieldKeys holds the default value on creation for the field_keys field.
	contenttype.DefaultFieldKeys = contenttypeDescFieldKeys.Default.([]string)
	// contenttypeDescRules is the schema descriptor for rules field.
	contenttypeDescRules := contenttypeFields[4].Descriptor()
	// contenttype.DefaultRules holds the default value on creation for the rules field.
	contenttype.DefaultRules = contenttypeDescRules.Default.([]model.ValidationRule)
	// contenttypeDescIsDefault is the schema descriptor for is_default field.
	contenttypeDescIsDefault := contenttypeFields[5].Descriptor()
	// contenttype.DefaultIsDefault holds the default value on creation for the is_default field.
	contenttype.DefaultIsDefault = contenttypeDescIsDefault.Default.(bool)
	// contenttypeDescVersion is the schema descriptor for version field.
	contenttypeDescVersion := contenttypeFields[6].Descriptor()
	// contenttype.DefaultVersion holds the default value on creation for the version field.
	contenttype.DefaultVersion = contenttypeDescVersion.Default.(int)
	// contenttype.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	contenttype.VersionValidator = contenttypeDescVersion.Validators[0].(func(int) error)
	// contenttypeDescUpdatedAt is the schema descriptor for updated_at field.
	contenttypeDescUpdatedAt := contenttypeFields[7].Descriptor()
	// contenttype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contenttype.DefaultUpdatedAt = contenttypeDescUpdatedAt.Default.(func() time.Time)
	// contenttype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contenttype.UpdateDefaultUpdatedAt = contenttypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// contenttypeDescID is the schema descriptor for id field.
	contenttypeDescID := contenttypeMixinFields0[0].Descriptor()
	// contenttype.DefaultID holds the default value on creation for the id field.
	contenttype.DefaultID = contenttypeDescID.Default.(func() string)
	// contenttype.IDValidator is a validator for the "id" field. It is called by the builders before save.
	contenttype.IDValidator = contenttypeDescID.Validators[0].(func(string) error)
	domaineventFields := schema.DomainEvent{}.Fields()
	_ = domaineventFields
	// domaineventDescCreatedAt is the schema descriptor for created_at field.
	domaineventDescCreatedAt := domaineventFields[1].Descriptor()
	// domainevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	domainevent.DefaultCreatedAt = domaineventDescCreatedAt.Default.(func() time.Time)
	// domaineventDescType is the schema descriptor for type field.
	domaineventDescType := domaineventFields[2].Descriptor()
	// domainevent.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	domainevent.TypeValidator = domaineventDescType.Validators[0].(func(string) error)
	// domaineventDescWorkspaceID is the schema descriptor for workspace_id field.
	domaineventDescWorkspaceID := domaineventFields[3].Descriptor()
	// domainevent.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	domainevent.WorkspaceIDValidator = domaineventDescWorkspaceID.Validators[0].(func(string) error)
	// domaineventDescData is the schema descriptor for data field.
	domaineventDescData := domaineventFields[7].Descriptor()
	// domainevent.DefaultData holds the default value on creation for the data field.
	domainevent.DefaultData = domaineventDescData.Default.(map[string]interface{})
	// domaineventDescDepth is the schema descriptor for depth field.
	domaineventDescDepth := domaineventFields[8].Descriptor()
	// domainevent.DepthValidator is a validator for the "depth" field. It is called by the builders before save.
	domainevent.DepthValidator = domaineventDescDepth.Validators[0].(func(int) error)
	fielddefinitionMixin := schema.FieldDefinition{}.Mixin()
	fielddefinitionMixinFields0 := fielddefinitionMixin[0].Fields()
	_ = fielddefinitionMixinFields0
	fielddefinitionFields := schema.FieldDefinition{}.Fields()
	_ = fielddefinitionFields
	// fielddefinitionDescCreatedAt is the schema descriptor for created_at field.
	fielddefinitionDescCreatedAt := fielddefinitionMixinFields0[1].Descriptor()
	// fielddefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	fielddefinition.DefaultCreatedAt = fielddefinitionDescCreatedAt.Default.(func() time.Time)
	// fielddefinitionDescContainerID is the schema descriptor for container_id field.
	fielddefinitionDescContainerID := fielddefinitionFields[0].Descriptor()
	// fielddefinition.ContainerIDValidator is a validator for the "container_id" field. It is called by the builders before save.
	fielddefinition.ContainerIDValidator = func() func(string) error {
		validators := fielddefinitionDescContainerID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(container string) error {
			for _, fn := range fns {
				if err := fn(container); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fielddefinitionDescKey is the schema descriptor for key field.
	fielddefinitionDescKey := fielddefinitionFields[1].Descriptor()
	// fielddefinition.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	fielddefinition.KeyValidator = func() func(string) error {
		validators := fielddefinitionDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fielddefinitionDescLabel is the schema descriptor for label field.
	fielddefinitionDescLabel := fielddefinitionFields[2].Descriptor()
	// fielddefinition.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	fielddefinition.LabelValidator = func() func(string) error {
		validators := fielddefinitionDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fielddefinitionDescOptions is the schema descriptor for options field.
	fielddefinitionDescOptions := fielddefinitionFields[4].Descriptor()
	// fielddefinition.DefaultOptions holds the default value on creation for the options field.
	fielddefinition.DefaultOptions = fielddefinitionDescOptions.Default.(model.FieldOptions)
	// fielddefinitionDescIndexed is the schema descriptor for indexed field.
	fielddefinitionDescIndexed := fielddefinitionFields[5].Descriptor()
	// fielddefinition.DefaultIndexed holds the default value on creation for the indexed field.
	fielddefinition.DefaultIndexed = fielddefinitionDescIndexed.Default.(bool)
	// fielddefinitionDescScale is the schema descriptor for scale field.
	fielddefinitionDescScale := fielddefinitionFields[6].Descriptor()
	// fielddefinition.DefaultScale holds the default value on creation for the scale field.
	fielddefinition.DefaultScale = fielddefinitionDescScale.Default.(int)
	// fielddefinition.ScaleValidator is a validator for the "scale" field. It is called by the builders before save.
	fielddefinition.ScaleValidator = func() func(int) error {
		validators := fielddefinitionDescScale.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(scale int) error {
			for _, fn := range fns {
				if err := fn(scale); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fielddefinitionDescRequired is the schema descriptor for required field.
	fielddefinitionDescRequired := fielddefinitionFields[7].Descriptor()
	// fielddefinition.DefaultRequired holds the default value on creation for the required field.
	fielddefinition.DefaultRequired = fielddefinitionDescRequired.Default.(bool)
	// fielddefinitionDescChoices is the schema descriptor for choices field.
	fielddefinitionDescChoices := fielddefinitionFields[8].Descriptor()
	// fielddefinition.DefaultChoices holds the default value on creation for the choices field.
	fielddefinition.DefaultChoices = fielddefinitionDescChoices.Default.([]string)
	// fielddefinitionDescID is the schema descriptor for id field.
	fielddefinitionDescID := fielddefinitionMixinFields0[0].Descriptor()
	// fielddefinition.DefaultID holds the default value on creation for the id field.
	fielddefinition.DefaultID = fielddefinitionDescID.Default.(func() string)
	// fielddefinition.IDValidator is a validator for the "id" field. It is called by the builders before save.
	fielddefinition.IDValidator = fielddefinitionDescID.Validators[0].(func(string) error)
	fieldvalueMixin := schema.FieldValue{}.Mixin()
	fieldvalueMixinFields0 := fieldvalueMixin[0].Fields()
	_ = fieldvalueMixinFields0
	fieldvalueFields := schema.FieldValue{}.Fields()
	_ = fieldvalueFields
	// fieldvalueDescCreatedAt is the schema descriptor for created_at field.
	fieldvalueDescCreatedAt := fieldvalueMixinFields0[1].Descriptor()
	// fieldvalue.DefaultCreatedAt holds the default value on creation for the created_at field.
	fieldvalue.DefaultCreatedAt = fieldvalueDescCreatedAt.Default.(func() time.Time)
	// fieldvalueDescOrdinal is the schema descriptor for ordinal field.
	fieldvalueDescOrdinal := fieldvalueFields[6].Descriptor()
	// fieldvalue.DefaultOrdinal holds the default value on creation for the ordinal field.
	fieldvalue.DefaultOrdinal = fieldvalueDescOrdinal.Default.(int)
	// fieldvalue.OrdinalValidator is a validator for the "ordinal" field. It is called by the builders before save.
	fieldvalue.OrdinalValidator = fieldvalueDescOrdinal.Validators[0].(func(int) error)
	// fieldvalueDescScale is the schema descriptor for scale field.
	fieldvalueDescScale := fieldvalueFields[7].Descriptor()
	// fieldvalue.DefaultScale holds the default value on creation for the scale field.
	fieldvalue.DefaultScale = fieldvalueDescScale.Default.(int)
	// fieldvalueDescID is the schema descriptor for id field.
	fieldvalueDescID := fieldvalueMixinFields0[0].Descriptor()
	// fieldvalue.DefaultID holds the default value on creation for the id field.
	fieldvalue.DefaultID = fieldvalueDescID.Default.(func() string)
	// fieldvalue.IDValidator is a validator for the "id" field. It is called by the builders before save.
	fieldvalue.IDValidator = fieldvalueDescID.Validators[0].(func(string) error)
	grantMixin := schema.Grant{}.Mixin()
	grantMixinFields0 := grantMixin[0].Fields()
	_ = grantMixinFields0
	grantFields := schema.Grant{}.Fields()
	_ = grantFields
	// grantDescCreatedAt is the schema descriptor for created_at field.
	grantDescCreatedAt := grantMixinFields0[1].Descriptor()
	// grant.DefaultCreatedAt holds the default value on creation for the created_at field.
	grant.DefaultCreatedAt = grantDescCreatedAt.Default.(func() time.Time)
	// grantDescResourceID is the schema descriptor for resource_id field.
	grantDescResourceID := grantFields[0].Descriptor()
	// grant.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	grant.ResourceIDValidator = func() func(string) error {
		validators := grantDescResourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource string) error {
			for _, fn := range fns {
				if err := fn(resource); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// grantDescSubject is the schema descriptor for subject field.
	grantDescSubject := grantFields[1].Descriptor()
	// grant.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	grant.SubjectValidator = func() func(string) error {
		validators := grantDescSubject.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject string) error {
			for _, fn := range fns {
				if err := fn(subject); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// grantDescID is the schema descriptor for id field.
	grantDescID := grantMixinFields0[0].Descriptor()
	// grant.DefaultID holds the default value on creation for the id field.
	grant.DefaultID = grantDescID.Default.(func() string)
	// grant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	grant.IDValidator = grantDescID.Validators[0].(func(string) error)
	itemrevisionMixin := schema.ItemRevision{}.Mixin()
	itemrevisionMixinFields0 := itemrevisionMixin[0].Fields()
	_ = itemrevisionMixinFields0
	itemrevisionFields := schema.ItemRevision{}.Fields()
	_ = itemrevisionFields
	// itemrevisionDescCreatedAt is the schema descriptor for created_at field.
	itemrevisionDescCreatedAt := itemrevisionMixinFields0[1].Descriptor()
	// itemrevision.DefaultCreatedAt holds the default value on creation for the created_at field.
	itemrevision.DefaultCreatedAt = itemrevisionDescCreatedAt.Default.(func() time.Time)
	// itemrevisionDescRevisionNumber is the schema descriptor for revision_number field.
	itemrevisionDescRevisionNumber := itemrevisionFields[5].Descriptor()
	// itemrevision.RevisionNumberValidator is a validator for the "revision_number" field. It is called by the builders before save.
	itemrevision.RevisionNumberValidator = itemrevisionDescRevisionNumber.Validators[0].(func(int) error)
	// itemrevisionDescName is the schema descriptor for name field.
	itemrevisionDescName := itemrevisionFields[6].Descriptor()
	// itemrevision.NameValidator is a validator for the "name" field. It is called by the builders before save.
	itemrevision.NameValidator = func() func(string) error {
		validators := itemrevisionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemrevisionDescCreatedBy is the schema descriptor for created_by field.
	itemrevisionDescCreatedBy := itemrevisionFields[9].Descriptor()
	// itemrevision.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	itemrevision.CreatedByValidator = itemrevisionDescCreatedBy.Validators[0].(func(string) error)
	// itemrevisionDescID is the schema descriptor for id field.
	itemrevisionDescID := itemrevisionMixinFields0[0].Descriptor()
	// itemrevision.DefaultID holds the default value on creation for the id field.
	itemrevision.DefaultID = itemrevisionDescID.Default.(func() string)
	// itemrevision.IDValidator is a validator for the "id" field. It is called by the builders before save.
	itemrevision.IDValidator = itemrevisionDescID.Validators[0].(func(string) error)
	itemsurfaceMixin := schema.ItemSurface{}.Mixin()
	itemsurfaceMixinFields0 := itemsurfaceMixin[0].Fields()
	_ = itemsurfaceMixinFields0
	itemsurfaceFields := schema.ItemSurface{}.Fields()
	_ = itemsurfaceFields
	// itemsurfaceDescCreatedAt is the schema descriptor for created_at field.
	itemsurfaceDescCreatedAt := itemsurfaceMixinFields0[1].Descriptor()
	// itemsurface.DefaultCreatedAt holds the default value on creation for the created_at field.
	itemsurface.DefaultCreatedAt = itemsurfaceDescCreatedAt.Default.(func() time.Time)
	// itemsurfaceDescTermText is the schema descriptor for term_text field.
	itemsurfaceDescTermText := itemsurfaceFields[8].Descriptor()
	// itemsurface.DefaultTermText holds the default value on creation for the term_text field.
	itemsurface.DefaultTermText = itemsurfaceDescTermText.Default.(string)
	// itemsurfaceDescID is the schema descriptor for id field.
	itemsurfaceDescID := itemsurfaceMixinFields0[0].Descriptor()
	// itemsurface.DefaultID holds the default value on creation for the id field.
	itemsurface.DefaultID = itemsurfaceDescID.Default.(func() string)
	// itemsurface.IDValidator is a validator for the "id" field. It is called by the builders before save.
	itemsurface.IDValidator = itemsurfaceDescID.Validators[0].(func(string) error)
	listviewMixin := schema.ListView{}.Mixin()
	listviewMixinFields0 := listviewMixin[0].Fields()
	_ = listviewMixinFields0
	listviewFields := schema.ListView{}.Fields()
	_ = listviewFields
	// listviewDescCreatedAt is the schema descriptor for created_at field.
	listviewDescCreatedAt := listviewMixinFields0[1].Descriptor()
	// listview.DefaultCreatedAt holds the default value on creation for the created_at field.
	listview.DefaultCreatedAt = listviewDescCreatedAt.Default.(func() time.Time)
	// listviewDescColumns is the schema descriptor for columns field.
	listviewDescColumns := listviewFields[2].Descriptor()
	// listview.DefaultColumns holds the default value on creation for the columns field.
	listview.DefaultColumns = listviewDescColumns.Default.([]string)
	// listviewDescLayout is the schema descriptor for layout field.
	listviewDescLayout := listviewFields[4].Descriptor()
	// listview.DefaultLayout holds the default value on creation for the layout field.
	listview.DefaultLayout = listviewDescLayout.Default.(string)
	// listviewDescIsDefault is the schema descriptor for is_default field.
	listviewDescIsDefault := listviewFields[5].Descriptor()
	// listview.DefaultIsDefault holds the default value on creation for the is_default field.
	listview.DefaultIsDefault = listviewDescIsDefault.Default.(bool)
	// listviewDescVersion is the schema descriptor for version field.
	listviewDescVersion := listviewFields[6].Descriptor()
	// listview.DefaultVersion holds the default value on creation for the version field.
	listview.DefaultVersion = listviewDescVersion.Default.(int)
	// listview.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	listview.VersionValidator = listviewDescVersion.Validators[0].(func(int) error)
	// listviewDescUpdatedAt is the schema descriptor for updated_at field.
	listviewDescUpdatedAt := listviewFields[7].Descriptor()
	// listview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listview.DefaultUpdatedAt = listviewDescUpdatedAt.Default.(func() time.Time)
	// listview.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listview.UpdateDefaultUpdatedAt = listviewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listviewDescID is the schema descriptor for id field.
	listviewDescID := listviewMixinFields0[0].Descriptor()
	// listview.DefaultID holds the default value on creation for the id field.
	listview.DefaultID = listviewDescID.Default.(func() string)
	// listview.IDValidator is a validator for the "id" field. It is called by the builders before save.
	listview.IDValidator = listviewDescID.Validators[0].(func(string) error)
	publicationMixin := schema.Publication{}.Mixin()
	publicationMixinFields0 := publicationMixin[0].Fields()
	_ = publicationMixinFields0
	publicationFields := schema.Publication{}.Fields()
	_ = publicationFields
	// publicationDescCreatedAt is the schema descriptor for created_at field.
	publicationDescCreatedAt := publicationMixinFields0[1].Descriptor()
	// publication.DefaultCreatedAt holds the default value on creation for the created_at field.
	publication.DefaultCreatedAt = publicationDescCreatedAt.Default.(func() time.Time)
	// publicationDescItemID is the schema descriptor for item_id field.
	publicationDescItemID := publicationFields[0].Descriptor()
	// publication.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	publication.ItemIDValidator = func() func(string) error {
		validators := publicationDescItemID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(item string) error {
			for _, fn := range fns {
				if err := fn(item); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// publicationDescVersion is the schema descriptor for version field.
	publicationDescVersion := publicationFields[1].Descriptor()
	// publication.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	publication.VersionValidator = publicationDescVersion.Validators[0].(func(int) error)
	// publicationDescPublishedBy is the schema descriptor for published_by field.
	publicationDescPublishedBy := publicationFields[4].Descriptor()
	// publication.PublishedByValidator is a validator for the "published_by" field. It is called by the builders before save.
	publication.PublishedByValidator = func() func(string) error {
		validators := publicationDescPublishedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(published_by string) error {
			for _, fn := range fns {
				if err := fn(published_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// publicationDescID is the schema descriptor for id field.
	publicationDescID := publicationMixinFields0[0].Descriptor()
	// publication.DefaultID holds the default value on creation for the id field.
	publication.DefaultID = publicationDescID.Default.(func() string)
	// publication.IDValidator is a validator for the "id" field. It is called by the builders before save.
	publication.IDValidator = publicationDescID.Validators[0].(func(string) error)
	relationshipMixin := schema.Relationship{}.Mixin()
	relationshipMixinFields0 := relationshipMixin[0].Fields()
	_ = relationshipMixinFields0
	relationshipFields := schema.Relationship{}.Fields()
	_ = relationshipFields
	// relationshipDescCreatedAt is the schema descriptor for created_at field.
	relationshipDescCreatedAt := relationshipMixinFields0[1].Descriptor()
	// relationship.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationship.DefaultCreatedAt = relationshipDescCreatedAt.Default.(func() time.Time)
	// relationshipDescWorkspaceID is the schema descriptor for workspace_id field.
	relationshipDescWorkspaceID := relationshipFields[0].Descriptor()
	// relationship.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	relationship.WorkspaceIDValidator = func() func(string) error {
		validators := relationshipDescWorkspaceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workspace_id string) error {
			for _, fn := range fns {
				if err := fn(workspace_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// relationshipDescSourceID is the schema descriptor for source_id field.
	relationshipDescSourceID := relationshipFields[1].Descriptor()
	// relationship.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	relationship.SourceIDValidator = func() func(string) error {
		validators := relationshipDescSourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(source string) error {
			for _, fn := range fns {
				if err := fn(source); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// relationshipDescTargetID is the schema descriptor for target_id field.
	relationshipDescTargetID := relationshipFields[2].Descriptor()
	// relationship.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	relationship.TargetIDValidator = func() func(string) error {
		validators := relationshipDescTargetID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target string) error {
			for _, fn := range fns {
				if err := fn(target); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// relationshipDescName is the schema descriptor for name field.
	relationshipDescName := relationshipFields[3].Descriptor()
	// relationship.NameValidator is a validator for the "name" field. It is called by the builders before save.
	relationship.NameValidator = func() func(string) error {
		validators := relationshipDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// relationshipDescTypeID is the schema descriptor for type_id field.
	relationshipDescTypeID := relationshipFields[4].Descriptor()
	// relationship.TypeIDValidator is a validator for the "type_id" field. It is called by the builders before save.
	relationship.TypeIDValidator = relationshipDescTypeID.Validators[0].(func(string) error)
	// relationshipDescDirected is the schema descriptor for directed field.
	relationshipDescDirected := relationshipFields[5].Descriptor()
	// relationship.DefaultDirected holds the default value on creation for the directed field.
	relationship.DefaultDirected = relationshipDescDirected.Default.(bool)
	// relationshipDescVersion is the schema descriptor for version field.
	relationshipDescVersion := relationshipFields[6].Descriptor()
	// relationship.DefaultVersion holds the default value on creation for the version field.
	relationship.DefaultVersion = relationshipDescVersion.Default.(int)
	// relationship.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	relationship.VersionValidator = relationshipDescVersion.Validators[0].(func(int) error)
	// relationshipDescMetadata is the schema descriptor for metadata field.
	relationshipDescMetadata := relationshipFields[7].Descriptor()
	// relationship.DefaultMetadata holds the default value on creation for the metadata field.
	relationship.DefaultMetadata = relationshipDescMetadata.Default.(map[string]interface{})
	// relationshipDescID is the schema descriptor for id field.
	relationshipDescID := relationshipMixinFields0[0].Descriptor()
	// relationship.DefaultID holds the default value on creation for the id field.
	relationship.DefaultID = relationshipDescID.Default.(func() string)
	// relationship.IDValidator is a validator for the "id" field. It is called by the builders before save.
	relationship.IDValidator = relationshipDescID.Validators[0].(func(string) error)
	relationshiptypeMixin := schema.RelationshipType{}.Mixin()
	relationshiptypeMixinFields0 := relationshiptypeMixin[0].Fields()
	_ = relationshiptypeMixinFields0
	relationshiptypeFields := schema.RelationshipType{}.Fields()
	_ = relationshiptypeFields
	// relationshiptypeDescCreatedAt is the schema descriptor for created_at field.
	relationshiptypeDescCreatedAt := relationshiptypeMixinFields0[1].Descriptor()
	// relationshiptype.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationshiptype.DefaultCreatedAt = relationshiptypeDescCreatedAt.Default.(func() time.Time)
	// relationshiptypeDescInverseLabel is the schema descriptor for inverse_label field.
	relationshiptypeDescInverseLabel := relationshiptypeFields[3].Descriptor()
	// relationshiptype.DefaultInverseLabel holds the default value on creation for the inverse_label field.
	relationshiptype.DefaultInverseLabel = relationshiptypeDescInverseLabel.Default.(string)
	// relationshiptypeDescDirected is the schema descriptor for directed field.
	relationshiptypeDescDirected := relationshiptypeFields[4].Descriptor()
	// relationshiptype.DefaultDirected holds the default value on creation for the directed field.
	relationshiptype.DefaultDirected = relationshiptypeDescDirected.Default.(bool)
	// relationshiptypeDescMaxIncoming is the schema descriptor for max_incoming field.
	relationshiptypeDescMaxIncoming := relationshiptypeFields[5].Descriptor()
	// relationshiptype.MaxIncomingValidator is a validator for the "max_incoming" field. It is called by the builders before save.
	relationshiptype.MaxIncomingValidator = relationshiptypeDescMaxIncoming.Validators[0].(func(int) error)
	// relationshiptypeDescMaxOutgoing is the schema descriptor for max_outgoing field.
	relationshiptypeDescMaxOutgoing := relationshiptypeFields[6].Descriptor()
	// relationshiptype.MaxOutgoingValidator is a validator for the "max_outgoing" field. It is called by the builders before save.
	relationshiptype.MaxOutgoingValidator = relationshiptypeDescMaxOutgoing.Validators[0].(func(int) error)
	// relationshiptypeDescVersion is the schema descriptor for version field.
	relationshiptypeDescVersion := relationshiptypeFields[8].Descriptor()
	// relationshiptype.DefaultVersion holds the default value on creation for the version field.
	relationshiptype.DefaultVersion = relationshiptypeDescVersion.Default.(int)
	// relationshiptype.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	relationshiptype.VersionValidator = relationshiptypeDescVersion.Validators[0].(func(int) error)
	// relationshiptypeDescUpdatedAt is the schema descriptor for updated_at field.
	relationshiptypeDescUpdatedAt := relationshiptypeFields[9].Descriptor()
	// relationshiptype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	relationshiptype.DefaultUpdatedAt = relationshiptypeDescUpdatedAt.Default.(func() time.Time)
	// relationshiptype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	relationshiptype.UpdateDefaultUpdatedAt = relationshiptypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// relationshiptypeDescID is the schema descriptor for id field.
	relationshiptypeDescID := relationshiptypeMixinFields0[0].Descriptor()
	// relationshiptype.DefaultID holds the default value on creation for the id field.
	relationshiptype.DefaultID = relationshiptypeDescID.Default.(func() string)
	// relationshiptype.IDValidator is a validator for the "id" field. It is called by the builders before save.
	relationshiptype.IDValidator = relationshiptypeDescID.Validators[0].(func(string) error)
	resourceMixin := schema.Resource{}.Mixin()
	resourceMixinFields0 := resourceMixin[0].Fields()
	_ = resourceMixinFields0
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceMixinFields0[1].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescWorkspaceID is the schema descriptor for workspace_id field.
	resourceDescWorkspaceID := resourceFields[0].Descriptor()
	// resource.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	resource.WorkspaceIDValidator = func() func(string) error {
		validators := resourceDescWorkspaceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workspace_id string) error {
			for _, fn := range fns {
				if err := fn(workspace_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// resourceDescParentID is the schema descriptor for parent_id field.
	resourceDescParentID := resourceFields[1].Descriptor()
	// resource.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	resource.ParentIDValidator = resourceDescParentID.Validators[0].(func(string) error)
	// resourceDescContainerID is the schema descriptor for container_id field.
	resourceDescContainerID := resourceFields[2].Descriptor()
	// resource.ContainerIDValidator is a validator for the "container_id" field. It is called by the builders before save.
	resource.ContainerIDValidator = resourceDescContainerID.Validators[0].(func(string) error)
	// resourceDescContentTypeID is the schema descriptor for content_type_id field.
	resourceDescContentTypeID := resourceFields[3].Descriptor()
	// resource.ContentTypeIDValidator is a validator for the "content_type_id" field. It is called by the builders before save.
	resource.ContentTypeIDValidator = resourceDescContentTypeID.Validators[0].(func(string) error)
	// resourceDescName is the schema descriptor for name field.
	resourceDescName := resourceFields[5].Descriptor()
	// resource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	resource.NameValidator = func() func(string) error {
		validators := resourceDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// resourceDescTags is the schema descriptor for tags field.
	resourceDescTags := resourceFields[6].Descriptor()
	// resource.DefaultTags holds the default value on creation for the tags field.
	resource.DefaultTags = resourceDescTags.Default.([]string)
	// resourceDescTemplateKeys is the schema descriptor for template_keys field.
	resourceDescTemplateKeys := resourceFields[7].Descriptor()
	// resource.DefaultTemplateKeys holds the default value on creation for the template_keys field.
	resource.DefaultTemplateKeys = resourceDescTemplateKeys.Default.([]string)
	// resourceDescValues is the schema descriptor for values field.
	resourceDescValues := resourceFields[8].Descriptor()
	// resource.DefaultValues holds the default value on creation for the values field.
	resource.DefaultValues = resourceDescValues.Default.(map[string]interface{})
	// resourceDescInheritPermissions is the schema descriptor for inherit_permissions field.
	resourceDescInheritPermissions := resourceFields[9].Descriptor()
	// resource.DefaultInheritPermissions holds the default value on creation for the inherit_permissions field.
	resource.DefaultInheritPermissions = resourceDescInheritPermissions.Default.(bool)
	// resourceDescVersion is the schema descriptor for version field.
	resourceDescVersion := resourceFields[10].Descriptor()
	// resource.DefaultVersion holds the default value on creation for the version field.
	resource.DefaultVersion = resourceDescVersion.Default.(int)
	// resource.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	resource.VersionValidator = resourceDescVersion.Validators[0].(func(int) error)
	// resourceDescNextRevisionNumber is the schema descriptor for next_revision_number field.
	resourceDescNextRevisionNumber := resourceFields[14].Descriptor()
	// resource.DefaultNextRevisionNumber holds the default value on creation for the next_revision_number field.
	resource.DefaultNextRevisionNumber = resourceDescNextRevisionNumber.Default.(int)
	// resource.NextRevisionNumberValidator is a validator for the "next_revision_number" field. It is called by the builders before save.
	resource.NextRevisionNumberValidator = resourceDescNextRevisionNumber.Validators[0].(func(int) error)
	// resourceDescPublishingEnabled is the schema descriptor for publishing_enabled field.
	resourceDescPublishingEnabled := resourceFields[15].Descriptor()
	// resource.DefaultPublishingEnabled holds the default value on creation for the publishing_enabled field.
	resource.DefaultPublishingEnabled = resourceDescPublishingEnabled.Default.(bool)
	// resourceDescWebdavEnabled is the schema descriptor for webdav_enabled field.
	resourceDescWebdavEnabled := resourceFields[16].Descriptor()
	// resource.DefaultWebdavEnabled holds the default value on creation for the webdav_enabled field.
	resource.DefaultWebdavEnabled = resourceDescWebdavEnabled.Default.(bool)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceFields[17].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resourceDescCreatedBy is the schema descriptor for created_by field.
	resourceDescCreatedBy := resourceFields[18].Descriptor()
	// resource.DefaultCreatedBy holds the default value on creation for the created_by field.
	resource.DefaultCreatedBy = resourceDescCreatedBy.Default.(string)
	// resourceDescUpdatedBy is the schema descriptor for updated_by field.
	resourceDescUpdatedBy := resourceFields[19].Descriptor()
	// resource.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	resource.DefaultUpdatedBy = resourceDescUpdatedBy.Default.(string)
	// resourceDescScopeID is the schema descriptor for scope_id field.
	resourceDescScopeID := resourceFields[20].Descriptor()
	// resource.ScopeIDValidator is a validator for the "scope_id" field. It is called by the builders before save.
	resource.ScopeIDValidator = resourceDescScopeID.Validators[0].(func(string) error)
	// resourceDescNameKey is the schema descriptor for name_key field.
	resourceDescNameKey := resourceFields[21].Descriptor()
	// resource.NameKeyValidator is a validator for the "name_key" field. It is called by the builders before save.
	resource.NameKeyValidator = resourceDescNameKey.Validators[0].(func(string) error)
	// resourceDescID is the schema descriptor for id field.
	resourceDescID := resourceMixinFields0[0].Descriptor()
	// resource.DefaultID holds the default value on creation for the id field.
	resource.DefaultID = resourceDescID.Default.(func() string)
	// resource.IDValidator is a validator for the "id" field. It is called by the builders before save.
	resource.IDValidator = resourceDescID.Validators[0].(func(string) error)
	schemarevisionMixin := schema.SchemaRevision{}.Mixin()
	schemarevisionMixinFields0 := schemarevisionMixin[0].Fields()
	_ = schemarevisionMixinFields0
	schemarevisionFields := schema.SchemaRevision{}.Fields()
	_ = schemarevisionFields
	// schemarevisionDescCreatedAt is the schema descriptor for created_at field.
	schemarevisionDescCreatedAt := schemarevisionMixinFields0[1].Descriptor()
	// schemarevision.DefaultCreatedAt holds the default value on creation for the created_at field.
	schemarevision.DefaultCreatedAt = schemarevisionDescCreatedAt.Default.(func() time.Time)
	// schemarevisionDescRevisionNumber is the schema descriptor for revision_number field.
	schemarevisionDescRevisionNumber := schemarevisionFields[1].Descriptor()
	// schemarevision.RevisionNumberValidator is a validator for the "revision_number" field. It is called by the builders before save.
	schemarevision.RevisionNumberValidator = schemarevisionDescRevisionNumber.Validators[0].(func(int) error)
	// schemarevisionDescCreatedBy is the schema descriptor for created_by field.
	schemarevisionDescCreatedBy := schemarevisionFields[3].Descriptor()
	// schemarevision.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	schemarevision.CreatedByValidator = schemarevisionDescCreatedBy.Validators[0].(func(string) error)
	// schemarevisionDescID is the schema descriptor for id field.
	schemarevisionDescID := schemarevisionMixinFields0[0].Descriptor()
	// schemarevision.DefaultID holds the default value on creation for the id field.
	schemarevision.DefaultID = schemarevisionDescID.Default.(func() string)
	// schemarevision.IDValidator is a validator for the "id" field. It is called by the builders before save.
	schemarevision.IDValidator = schemarevisionDescID.Validators[0].(func(string) error)
	schematemplateMixin := schema.SchemaTemplate{}.Mixin()
	schematemplateMixinFields0 := schematemplateMixin[0].Fields()
	_ = schematemplateMixinFields0
	schematemplateFields := schema.SchemaTemplate{}.Fields()
	_ = schematemplateFields
	// schematemplateDescCreatedAt is the schema descriptor for created_at field.
	schematemplateDescCreatedAt := schematemplateMixinFields0[1].Descriptor()
	// schematemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	schematemplate.DefaultCreatedAt = schematemplateDescCreatedAt.Default.(func() time.Time)
	// schematemplateDescDescription is the schema descriptor for description field.
	schematemplateDescDescription := schematemplateFields[3].Descriptor()
	// schematemplate.DefaultDescription holds the default value on creation for the description field.
	schematemplate.DefaultDescription = schematemplateDescDescription.Default.(string)
	// schematemplateDescVersion is the schema descriptor for version field.
	schematemplateDescVersion := schematemplateFields[5].Descriptor()
	// schematemplate.DefaultVersion holds the default value on creation for the version field.
	schematemplate.DefaultVersion = schematemplateDescVersion.Default.(int)
	// schematemplate.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	schematemplate.VersionValidator = schematemplateDescVersion.Validators[0].(func(int) error)
	// schematemplateDescUpdatedAt is the schema descriptor for updated_at field.
	schematemplateDescUpdatedAt := schematemplateFields[6].Descriptor()
	// schematemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schematemplate.DefaultUpdatedAt = schematemplateDescUpdatedAt.Default.(func() time.Time)
	// schematemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schematemplate.UpdateDefaultUpdatedAt = schematemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// schematemplateDescID is the schema descriptor for id field.
	schematemplateDescID := schematemplateMixinFields0[0].Descriptor()
	// schematemplate.DefaultID holds the default value on creation for the id field.
	schematemplate.DefaultID = schematemplateDescID.Default.(func() string)
	// schematemplate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	schematemplate.IDValidator = schematemplateDescID.Validators[0].(func(string) error)
	smartfolderMixin := schema.SmartFolder{}.Mixin()
	smartfolderMixinFields0 := smartfolderMixin[0].Fields()
	_ = smartfolderMixinFields0
	smartfolderFields := schema.SmartFolder{}.Fields()
	_ = smartfolderFields
	// smartfolderDescCreatedAt is the schema descriptor for created_at field.
	smartfolderDescCreatedAt := smartfolderMixinFields0[1].Descriptor()
	// smartfolder.DefaultCreatedAt holds the default value on creation for the created_at field.
	smartfolder.DefaultCreatedAt = smartfolderDescCreatedAt.Default.(func() time.Time)
	// smartfolderDescWorkspaceID is the schema descriptor for workspace_id field.
	smartfolderDescWorkspaceID := smartfolderFields[0].Descriptor()
	// smartfolder.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	smartfolder.WorkspaceIDValidator = smartfolderDescWorkspaceID.Validators[0].(func(string) error)
	// smartfolderDescOwnerID is the schema descriptor for owner_id field.
	smartfolderDescOwnerID := smartfolderFields[1].Descriptor()
	// smartfolder.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	smartfolder.OwnerIDValidator = smartfolderDescOwnerID.Validators[0].(func(string) error)
	// smartfolderDescName is the schema descriptor for name field.
	smartfolderDescName := smartfolderFields[2].Descriptor()
	// smartfolder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	smartfolder.NameValidator = func() func(string) error {
		validators := smartfolderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// smartfolderDescDescription is the schema descriptor for description field.
	smartfolderDescDescription := smartfolderFields[3].Descriptor()
	// smartfolder.DefaultDescription holds the default value on creation for the description field.
	smartfolder.DefaultDescription = smartfolderDescDescription.Default.(string)
	// smartfolderDescUpdatedAt is the schema descriptor for updated_at field.
	smartfolderDescUpdatedAt := smartfolderFields[7].Descriptor()
	// smartfolder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	smartfolder.DefaultUpdatedAt = smartfolderDescUpdatedAt.Default.(func() time.Time)
	// smartfolder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	smartfolder.UpdateDefaultUpdatedAt = smartfolderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// smartfolderDescVersion is the schema descriptor for version field.
	smartfolderDescVersion := smartfolderFields[8].Descriptor()
	// smartfolder.DefaultVersion holds the default value on creation for the version field.
	smartfolder.DefaultVersion = smartfolderDescVersion.Default.(int)
	// smartfolder.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	smartfolder.VersionValidator = smartfolderDescVersion.Validators[0].(func(int) error)
	// smartfolderDescID is the schema descriptor for id field.
	smartfolderDescID := smartfolderMixinFields0[0].Descriptor()
	// smartfolder.DefaultID holds the default value on creation for the id field.
	smartfolder.DefaultID = smartfolderDescID.Default.(func() string)
	// smartfolder.IDValidator is a validator for the "id" field. It is called by the builders before save.
	smartfolder.IDValidator = smartfolderDescID.Validators[0].(func(string) error)
	termMixin := schema.Term{}.Mixin()
	termMixinFields0 := termMixin[0].Fields()
	_ = termMixinFields0
	termFields := schema.Term{}.Fields()
	_ = termFields
	// termDescCreatedAt is the schema descriptor for created_at field.
	termDescCreatedAt := termMixinFields0[1].Descriptor()
	// term.DefaultCreatedAt holds the default value on creation for the created_at field.
	term.DefaultCreatedAt = termDescCreatedAt.Default.(func() time.Time)
	// termDescDescription is the schema descriptor for description field.
	termDescDescription := termFields[4].Descriptor()
	// term.DefaultDescription holds the default value on creation for the description field.
	term.DefaultDescription = termDescDescription.Default.(string)
	// termDescSortOrder is the schema descriptor for sort_order field.
	termDescSortOrder := termFields[6].Descriptor()
	// term.DefaultSortOrder holds the default value on creation for the sort_order field.
	term.DefaultSortOrder = termDescSortOrder.Default.(int)
	// termDescLabels is the schema descriptor for labels field.
	termDescLabels := termFields[8].Descriptor()
	// term.DefaultLabels holds the default value on creation for the labels field.
	term.DefaultLabels = termDescLabels.Default.(map[string]string)
	// termDescSynonyms is the schema descriptor for synonyms field.
	termDescSynonyms := termFields[9].Descriptor()
	// term.DefaultSynonyms holds the default value on creation for the synonyms field.
	term.DefaultSynonyms = termDescSynonyms.Default.([]string)
	// termDescAvailableAsKeyword is the schema descriptor for available_as_keyword field.
	termDescAvailableAsKeyword := termFields[11].Descriptor()
	// term.DefaultAvailableAsKeyword holds the default value on creation for the available_as_keyword field.
	term.DefaultAvailableAsKeyword = termDescAvailableAsKeyword.Default.(bool)
	// termDescDeprecated is the schema descriptor for deprecated field.
	termDescDeprecated := termFields[12].Descriptor()
	// term.DefaultDeprecated holds the default value on creation for the deprecated field.
	term.DefaultDeprecated = termDescDeprecated.Default.(bool)
	// termDescVersion is the schema descriptor for version field.
	termDescVersion := termFields[13].Descriptor()
	// term.DefaultVersion holds the default value on creation for the version field.
	term.DefaultVersion = termDescVersion.Default.(int)
	// term.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	term.VersionValidator = termDescVersion.Validators[0].(func(int) error)
	// termDescUpdatedAt is the schema descriptor for updated_at field.
	termDescUpdatedAt := termFields[14].Descriptor()
	// term.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	term.DefaultUpdatedAt = termDescUpdatedAt.Default.(func() time.Time)
	// term.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	term.UpdateDefaultUpdatedAt = termDescUpdatedAt.UpdateDefault.(func() time.Time)
	// termDescID is the schema descriptor for id field.
	termDescID := termMixinFields0[0].Descriptor()
	// term.DefaultID holds the default value on creation for the id field.
	term.DefaultID = termDescID.Default.(func() string)
	// term.IDValidator is a validator for the "id" field. It is called by the builders before save.
	term.IDValidator = termDescID.Validators[0].(func(string) error)
	termgroupMixin := schema.TermGroup{}.Mixin()
	termgroupMixinFields0 := termgroupMixin[0].Fields()
	_ = termgroupMixinFields0
	termgroupFields := schema.TermGroup{}.Fields()
	_ = termgroupFields
	// termgroupDescCreatedAt is the schema descriptor for created_at field.
	termgroupDescCreatedAt := termgroupMixinFields0[1].Descriptor()
	// termgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	termgroup.DefaultCreatedAt = termgroupDescCreatedAt.Default.(func() time.Time)
	// termgroupDescDescription is the schema descriptor for description field.
	termgroupDescDescription := termgroupFields[2].Descriptor()
	// termgroup.DefaultDescription holds the default value on creation for the description field.
	termgroup.DefaultDescription = termgroupDescDescription.Default.(string)
	// termgroupDescIsSystem is the schema descriptor for is_system field.
	termgroupDescIsSystem := termgroupFields[3].Descriptor()
	// termgroup.DefaultIsSystem holds the default value on creation for the is_system field.
	termgroup.DefaultIsSystem = termgroupDescIsSystem.Default.(bool)
	// termgroupDescVersion is the schema descriptor for version field.
	termgroupDescVersion := termgroupFields[4].Descriptor()
	// termgroup.DefaultVersion holds the default value on creation for the version field.
	termgroup.DefaultVersion = termgroupDescVersion.Default.(int)
	// termgroup.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	termgroup.VersionValidator = termgroupDescVersion.Validators[0].(func(int) error)
	// termgroupDescUpdatedAt is the schema descriptor for updated_at field.
	termgroupDescUpdatedAt := termgroupFields[5].Descriptor()
	// termgroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	termgroup.DefaultUpdatedAt = termgroupDescUpdatedAt.Default.(func() time.Time)
	// termgroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	termgroup.UpdateDefaultUpdatedAt = termgroupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// termgroupDescID is the schema descriptor for id field.
	termgroupDescID := termgroupMixinFields0[0].Descriptor()
	// termgroup.DefaultID holds the default value on creation for the id field.
	termgroup.DefaultID = termgroupDescID.Default.(func() string)
	// termgroup.IDValidator is a validator for the "id" field. It is called by the builders before save.
	termgroup.IDValidator = termgroupDescID.Validators[0].(func(string) error)
	termsetMixin := schema.TermSet{}.Mixin()
	termsetMixinFields0 := termsetMixin[0].Fields()
	_ = termsetMixinFields0
	termsetFields := schema.TermSet{}.Fields()
	_ = termsetFields
	// termsetDescCreatedAt is the schema descriptor for created_at field.
	termsetDescCreatedAt := termsetMixinFields0[1].Descriptor()
	// termset.DefaultCreatedAt holds the default value on creation for the created_at field.
	termset.DefaultCreatedAt = termsetDescCreatedAt.Default.(func() time.Time)
	// termsetDescDescription is the schema descriptor for description field.
	termsetDescDescription := termsetFields[4].Descriptor()
	// termset.DefaultDescription holds the default value on creation for the description field.
	termset.DefaultDescription = termsetDescDescription.Default.(string)
	// termsetDescIsOpen is the schema descriptor for is_open field.
	termsetDescIsOpen := termsetFields[5].Descriptor()
	// termset.DefaultIsOpen holds the default value on creation for the is_open field.
	termset.DefaultIsOpen = termsetDescIsOpen.Default.(bool)
	// termsetDescIsKeywords is the schema descriptor for is_keywords field.
	termsetDescIsKeywords := termsetFields[6].Descriptor()
	// termset.DefaultIsKeywords holds the default value on creation for the is_keywords field.
	termset.DefaultIsKeywords = termsetDescIsKeywords.Default.(bool)
	// termsetDescVersion is the schema descriptor for version field.
	termsetDescVersion := termsetFields[7].Descriptor()
	// termset.DefaultVersion holds the default value on creation for the version field.
	termset.DefaultVersion = termsetDescVersion.Default.(int)
	// termset.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	termset.VersionValidator = termsetDescVersion.Validators[0].(func(int) error)
	// termsetDescUpdatedAt is the schema descriptor for updated_at field.
	termsetDescUpdatedAt := termsetFields[8].Descriptor()
	// termset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	termset.DefaultUpdatedAt = termsetDescUpdatedAt.Default.(func() time.Time)
	// termset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	termset.UpdateDefaultUpdatedAt = termsetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// termsetDescID is the schema descriptor for id field.
	termsetDescID := termsetMixinFields0[0].Descriptor()
	// termset.DefaultID holds the default value on creation for the id field.
	termset.DefaultID = termsetDescID.Default.(func() string)
	// termset.IDValidator is a validator for the "id" field. It is called by the builders before save.
	termset.IDValidator = termsetDescID.Validators[0].(func(string) error)
	webdavcredentialMixin := schema.WebDAVCredential{}.Mixin()
	webdavcredentialMixinFields0 := webdavcredentialMixin[0].Fields()
	_ = webdavcredentialMixinFields0
	webdavcredentialFields := schema.WebDAVCredential{}.Fields()
	_ = webdavcredentialFields
	// webdavcredentialDescCreatedAt is the schema descriptor for created_at field.
	webdavcredentialDescCreatedAt := webdavcredentialMixinFields0[1].Descriptor()
	// webdavcredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	webdavcredential.DefaultCreatedAt = webdavcredentialDescCreatedAt.Default.(func() time.Time)
	// webdavcredentialDescSubject is the schema descriptor for subject field.
	webdavcredentialDescSubject := webdavcredentialFields[0].Descriptor()
	// webdavcredential.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	webdavcredential.SubjectValidator = func() func(string) error {
		validators := webdavcredentialDescSubject.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject string) error {
			for _, fn := range fns {
				if err := fn(subject); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// webdavcredentialDescLabel is the schema descriptor for label field.
	webdavcredentialDescLabel := webdavcredentialFields[1].Descriptor()
	// webdavcredential.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	webdavcredential.LabelValidator = func() func(string) error {
		validators := webdavcredentialDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// webdavcredentialDescSecretHash is the schema descriptor for secret_hash field.
	webdavcredentialDescSecretHash := webdavcredentialFields[2].Descriptor()
	// webdavcredential.SecretHashValidator is a validator for the "secret_hash" field. It is called by the builders before save.
	webdavcredential.SecretHashValidator = func() func(string) error {
		validators := webdavcredentialDescSecretHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(secret_hash string) error {
			for _, fn := range fns {
				if err := fn(secret_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// webdavcredentialDescID is the schema descriptor for id field.
	webdavcredentialDescID := webdavcredentialMixinFields0[0].Descriptor()
	// webdavcredential.DefaultID holds the default value on creation for the id field.
	webdavcredential.DefaultID = webdavcredentialDescID.Default.(func() string)
	// webdavcredential.IDValidator is a validator for the "id" field. It is called by the builders before save.
	webdavcredential.IDValidator = webdavcredentialDescID.Validators[0].(func(string) error)
	workflowMixin := schema.Workflow{}.Mixin()
	workflowMixinFields0 := workflowMixin[0].Fields()
	_ = workflowMixinFields0
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescCreatedAt is the schema descriptor for created_at field.
	workflowDescCreatedAt := workflowMixinFields0[1].Descriptor()
	// workflow.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflow.DefaultCreatedAt = workflowDescCreatedAt.Default.(func() time.Time)
	// workflowDescUpdatedAt is the schema descriptor for updated_at field.
	workflowDescUpdatedAt := workflowFields[0].Descriptor()
	// workflow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workflow.DefaultUpdatedAt = workflowDescUpdatedAt.Default.(func() time.Time)
	// workflowDescWorkspaceID is the schema descriptor for workspace_id field.
	workflowDescWorkspaceID := workflowFields[1].Descriptor()
	// workflow.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	workflow.WorkspaceIDValidator = func() func(string) error {
		validators := workflowDescWorkspaceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workspace_id string) error {
			for _, fn := range fns {
				if err := fn(workspace_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowDescKey is the schema descriptor for key field.
	workflowDescKey := workflowFields[2].Descriptor()
	// workflow.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	workflow.KeyValidator = func() func(string) error {
		validators := workflowDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowDescName is the schema descriptor for name field.
	workflowDescName := workflowFields[3].Descriptor()
	// workflow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workflow.NameValidator = func() func(string) error {
		validators := workflowDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowDescDescription is the schema descriptor for description field.
	workflowDescDescription := workflowFields[4].Descriptor()
	// workflow.DefaultDescription holds the default value on creation for the description field.
	workflow.DefaultDescription = workflowDescDescription.Default.(string)
	// workflowDescEnabled is the schema descriptor for enabled field.
	workflowDescEnabled := workflowFields[5].Descriptor()
	// workflow.DefaultEnabled holds the default value on creation for the enabled field.
	workflow.DefaultEnabled = workflowDescEnabled.Default.(bool)
	// workflowDescCollectionID is the schema descriptor for collection_id field.
	workflowDescCollectionID := workflowFields[7].Descriptor()
	// workflow.CollectionIDValidator is a validator for the "collection_id" field. It is called by the builders before save.
	workflow.CollectionIDValidator = workflowDescCollectionID.Validators[0].(func(string) error)
	// workflowDescParameters is the schema descriptor for parameters field.
	workflowDescParameters := workflowFields[8].Descriptor()
	// workflow.DefaultParameters holds the default value on creation for the parameters field.
	workflow.DefaultParameters = workflowDescParameters.Default.(map[string]interface{})
	// workflowDescCurrentVersion is the schema descriptor for current_version field.
	workflowDescCurrentVersion := workflowFields[9].Descriptor()
	// workflow.CurrentVersionValidator is a validator for the "current_version" field. It is called by the builders before save.
	workflow.CurrentVersionValidator = workflowDescCurrentVersion.Validators[0].(func(int) error)
	// workflowDescVersion is the schema descriptor for version field.
	workflowDescVersion := workflowFields[13].Descriptor()
	// workflow.DefaultVersion holds the default value on creation for the version field.
	workflow.DefaultVersion = workflowDescVersion.Default.(int)
	// workflow.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	workflow.VersionValidator = workflowDescVersion.Validators[0].(func(int) error)
	// workflowDescID is the schema descriptor for id field.
	workflowDescID := workflowMixinFields0[0].Descriptor()
	// workflow.DefaultID holds the default value on creation for the id field.
	workflow.DefaultID = workflowDescID.Default.(func() string)
	// workflow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workflow.IDValidator = workflowDescID.Validators[0].(func(string) error)
	workflowrunFields := schema.WorkflowRun{}.Fields()
	_ = workflowrunFields
	// workflowrunDescCreatedAt is the schema descriptor for created_at field.
	workflowrunDescCreatedAt := workflowrunFields[1].Descriptor()
	// workflowrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflowrun.DefaultCreatedAt = workflowrunDescCreatedAt.Default.(func() time.Time)
	// workflowrunDescWorkflowID is the schema descriptor for workflow_id field.
	workflowrunDescWorkflowID := workflowrunFields[2].Descriptor()
	// workflowrun.WorkflowIDValidator is a validator for the "workflow_id" field. It is called by the builders before save.
	workflowrun.WorkflowIDValidator = func() func(string) error {
		validators := workflowrunDescWorkflowID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workflow_id string) error {
			for _, fn := range fns {
				if err := fn(workflow_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowrunDescWorkflowVersion is the schema descriptor for workflow_version field.
	workflowrunDescWorkflowVersion := workflowrunFields[3].Descriptor()
	// workflowrun.WorkflowVersionValidator is a validator for the "workflow_version" field. It is called by the builders before save.
	workflowrun.WorkflowVersionValidator = workflowrunDescWorkflowVersion.Validators[0].(func(int) error)
	// workflowrunDescWorkspaceID is the schema descriptor for workspace_id field.
	workflowrunDescWorkspaceID := workflowrunFields[4].Descriptor()
	// workflowrun.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	workflowrun.WorkspaceIDValidator = func() func(string) error {
		validators := workflowrunDescWorkspaceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workspace_id string) error {
			for _, fn := range fns {
				if err := fn(workspace_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowrunDescItemID is the schema descriptor for item_id field.
	workflowrunDescItemID := workflowrunFields[5].Descriptor()
	// workflowrun.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	workflowrun.ItemIDValidator = workflowrunDescItemID.Validators[0].(func(string) error)
	// workflowrunDescEventID is the schema descriptor for event_id field.
	workflowrunDescEventID := workflowrunFields[6].Descriptor()
	// workflowrun.EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	workflowrun.EventIDValidator = workflowrunDescEventID.Validators[0].(func(string) error)
	// workflowrunDescEventType is the schema descriptor for event_type field.
	workflowrunDescEventType := workflowrunFields[7].Descriptor()
	// workflowrun.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	workflowrun.EventTypeValidator = workflowrunDescEventType.Validators[0].(func(string) error)
	// workflowrunDescDepth is the schema descriptor for depth field.
	workflowrunDescDepth := workflowrunFields[8].Descriptor()
	// workflowrun.DepthValidator is a validator for the "depth" field. It is called by the builders before save.
	workflowrun.DepthValidator = workflowrunDescDepth.Validators[0].(func(int) error)
	workflowrunitemFields := schema.WorkflowRunItem{}.Fields()
	_ = workflowrunitemFields
	// workflowrunitemDescRunID is the schema descriptor for run_id field.
	workflowrunitemDescRunID := workflowrunitemFields[1].Descriptor()
	// workflowrunitem.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	workflowrunitem.RunIDValidator = workflowrunitemDescRunID.Validators[0].(func(string) error)
	// workflowrunitemDescItemID is the schema descriptor for item_id field.
	workflowrunitemDescItemID := workflowrunitemFields[2].Descriptor()
	// workflowrunitem.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	workflowrunitem.ItemIDValidator = func() func(string) error {
		validators := workflowrunitemDescItemID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(item_id string) error {
			for _, fn := range fns {
				if err := fn(item_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowrunitemDescPosition is the schema descriptor for position field.
	workflowrunitemDescPosition := workflowrunitemFields[3].Descriptor()
	// workflowrunitem.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	workflowrunitem.PositionValidator = workflowrunitemDescPosition.Validators[0].(func(int) error)
	workflowtriggerMixin := schema.WorkflowTrigger{}.Mixin()
	workflowtriggerMixinFields0 := workflowtriggerMixin[0].Fields()
	_ = workflowtriggerMixinFields0
	workflowtriggerFields := schema.WorkflowTrigger{}.Fields()
	_ = workflowtriggerFields
	// workflowtriggerDescCreatedAt is the schema descriptor for created_at field.
	workflowtriggerDescCreatedAt := workflowtriggerMixinFields0[1].Descriptor()
	// workflowtrigger.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflowtrigger.DefaultCreatedAt = workflowtriggerDescCreatedAt.Default.(func() time.Time)
	// workflowtriggerDescWorkflowID is the schema descriptor for workflow_id field.
	workflowtriggerDescWorkflowID := workflowtriggerFields[0].Descriptor()
	// workflowtrigger.WorkflowIDValidator is a validator for the "workflow_id" field. It is called by the builders before save.
	workflowtrigger.WorkflowIDValidator = func() func(string) error {
		validators := workflowtriggerDescWorkflowID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workflow_id string) error {
			for _, fn := range fns {
				if err := fn(workflow_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowtriggerDescWorkspaceID is the schema descriptor for workspace_id field.
	workflowtriggerDescWorkspaceID := workflowtriggerFields[1].Descriptor()
	// workflowtrigger.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	workflowtrigger.WorkspaceIDValidator = func() func(string) error {
		validators := workflowtriggerDescWorkspaceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workspace_id string) error {
			for _, fn := range fns {
				if err := fn(workspace_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowtriggerDescCollectionID is the schema descriptor for collection_id field.
	workflowtriggerDescCollectionID := workflowtriggerFields[2].Descriptor()
	// workflowtrigger.CollectionIDValidator is a validator for the "collection_id" field. It is called by the builders before save.
	workflowtrigger.CollectionIDValidator = workflowtriggerDescCollectionID.Validators[0].(func(string) error)
	// workflowtriggerDescType is the schema descriptor for type field.
	workflowtriggerDescType := workflowtriggerFields[3].Descriptor()
	// workflowtrigger.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	workflowtrigger.TypeValidator = workflowtriggerDescType.Validators[0].(func(string) error)
	// workflowtriggerDescPosition is the schema descriptor for position field.
	workflowtriggerDescPosition := workflowtriggerFields[4].Descriptor()
	// workflowtrigger.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	workflowtrigger.PositionValidator = workflowtriggerDescPosition.Validators[0].(func(int) error)
	// workflowtriggerDescID is the schema descriptor for id field.
	workflowtriggerDescID := workflowtriggerMixinFields0[0].Descriptor()
	// workflowtrigger.DefaultID holds the default value on creation for the id field.
	workflowtrigger.DefaultID = workflowtriggerDescID.Default.(func() string)
	// workflowtrigger.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workflowtrigger.IDValidator = workflowtriggerDescID.Validators[0].(func(string) error)
	workflowversionMixin := schema.WorkflowVersion{}.Mixin()
	workflowversionMixinFields0 := workflowversionMixin[0].Fields()
	_ = workflowversionMixinFields0
	workflowversionFields := schema.WorkflowVersion{}.Fields()
	_ = workflowversionFields
	// workflowversionDescCreatedAt is the schema descriptor for created_at field.
	workflowversionDescCreatedAt := workflowversionMixinFields0[1].Descriptor()
	// workflowversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflowversion.DefaultCreatedAt = workflowversionDescCreatedAt.Default.(func() time.Time)
	// workflowversionDescWorkflowID is the schema descriptor for workflow_id field.
	workflowversionDescWorkflowID := workflowversionFields[0].Descriptor()
	// workflowversion.WorkflowIDValidator is a validator for the "workflow_id" field. It is called by the builders before save.
	workflowversion.WorkflowIDValidator = func() func(string) error {
		validators := workflowversionDescWorkflowID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(workflow_id string) error {
			for _, fn := range fns {
				if err := fn(workflow_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// workflowversionDescNumber is the schema descriptor for number field.
	workflowversionDescNumber := workflowversionFields[1].Descriptor()
	// workflowversion.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	workflowversion.NumberValidator = workflowversionDescNumber.Validators[0].(func(int) error)
	// workflowversionDescID is the schema descriptor for id field.
	workflowversionDescID := workflowversionMixinFields0[0].Descriptor()
	// workflowversion.DefaultID holds the default value on creation for the id field.
	workflowversion.DefaultID = workflowversionDescID.Default.(func() string)
	// workflowversion.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workflowversion.IDValidator = workflowversionDescID.Validators[0].(func(string) error)
}
