// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"papergo/ent/resource"
	"papergo/ent/schematemplate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaTemplateCreate is the builder for creating a SchemaTemplate entity.
type SchemaTemplateCreate struct {
	config
	mutation *SchemaTemplateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SchemaTemplateCreate) SetCreatedAt(v time.Time) *SchemaTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SchemaTemplateCreate) SetNillableCreatedAt(v *time.Time) *SchemaTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *SchemaTemplateCreate) SetWorkspaceID(v string) *SchemaTemplateCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *SchemaTemplateCreate) SetKey(v string) *SchemaTemplateCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SchemaTemplateCreate) SetName(v string) *SchemaTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SchemaTemplateCreate) SetDescription(v string) *SchemaTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SchemaTemplateCreate) SetNillableDescription(v *string) *SchemaTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDefinition sets the "definition" field.
func (_c *SchemaTemplateCreate) SetDefinition(v jsontext.Value) *SchemaTemplateCreate {
	_c.mutation.SetDefinition(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SchemaTemplateCreate) SetVersion(v int) *SchemaTemplateCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SchemaTemplateCreate) SetNillableVersion(v *int) *SchemaTemplateCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SchemaTemplateCreate) SetUpdatedAt(v time.Time) *SchemaTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SchemaTemplateCreate) SetNillableUpdatedAt(v *time.Time) *SchemaTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SchemaTemplateCreate) SetID(v string) *SchemaTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SchemaTemplateCreate) SetNillableID(v *string) *SchemaTemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkspace sets the "workspace" edge to the Resource entity.
func (_c *SchemaTemplateCreate) SetWorkspace(v *Resource) *SchemaTemplateCreate {
	return _c.SetWorkspaceID(v.ID)
}

// Mutation returns the SchemaTemplateMutation object of the builder.
func (_c *SchemaTemplateCreate) Mutation() *SchemaTemplateMutation {
	return _c.mutation
}

// Save creates the SchemaTemplate in the database.
func (_c *SchemaTemplateCreate) Save(ctx context.Context) (*SchemaTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchemaTemplateCreate) SaveX(ctx context.Context) *SchemaTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchemaTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := schematemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := schematemplate.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := schematemplate.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := schematemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := schematemplate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchemaTemplateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SchemaTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "SchemaTemplate.workspace_id"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SchemaTemplate.key"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SchemaTemplate.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "SchemaTemplate.description"`)}
	}
	if _, ok := _c.mutation.Definition(); !ok {
		return &ValidationError{Name: "definition", err: errors.New(`ent: missing required field "SchemaTemplate.definition"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SchemaTemplate.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := schematemplate.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SchemaTemplate.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SchemaTemplate.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := schematemplate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SchemaTemplate.id": %w`, err)}
		}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "SchemaTemplate.workspace"`)}
	}
	return nil
}

func (_c *SchemaTemplateCreate) sqlSave(ctx context.Context) (*SchemaTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SchemaTemplate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchemaTemplateCreate) createSpec() (*SchemaTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &SchemaTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schematemplate.Table, sqlgraph.NewFieldSpec(schematemplate.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(schematemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(schematemplate.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(schematemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(schematemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Definition(); ok {
		_spec.SetField(schematemplate.FieldDefinition, field.TypeJSON, value)
		_node.Definition = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(schematemplate.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(schematemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   schematemplate.WorkspaceTable,
			Columns: []string{schematemplate.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SchemaTemplateCreateBulk is the builder for creating many SchemaTemplate entities in bulk.
type SchemaTemplateCreateBulk struct {
	config
	err      error
	builders []*SchemaTemplateCreate
}

// Save creates the SchemaTemplate entities in the database.
func (_c *SchemaTemplateCreateBulk) Save(ctx context.Context) ([]*SchemaTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SchemaTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchemaTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchemaTemplateCreateBulk) SaveX(ctx context.Context) []*SchemaTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
