// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"papergo/ent/predicate"
	"papergo/ent/schematemplate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SchemaTemplateUpdate is the builder for updating SchemaTemplate entities.
type SchemaTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *SchemaTemplateMutation
}

// Where appends a list predicates to the SchemaTemplateUpdate builder.
func (_u *SchemaTemplateUpdate) Where(ps ...predicate.SchemaTemplate) *SchemaTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SchemaTemplateUpdate) SetName(v string) *SchemaTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchemaTemplateUpdate) SetNillableName(v *string) *SchemaTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SchemaTemplateUpdate) SetDescription(v string) *SchemaTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SchemaTemplateUpdate) SetNillableDescription(v *string) *SchemaTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *SchemaTemplateUpdate) SetDefinition(v jsontext.Value) *SchemaTemplateUpdate {
	_u.mutation.SetDefinition(v)
	return _u
}

// AppendDefinition appends value to the "definition" field.
func (_u *SchemaTemplateUpdate) AppendDefinition(v jsontext.Value) *SchemaTemplateUpdate {
	_u.mutation.AppendDefinition(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *SchemaTemplateUpdate) SetVersion(v int) *SchemaTemplateUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SchemaTemplateUpdate) SetNillableVersion(v *int) *SchemaTemplateUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SchemaTemplateUpdate) AddVersion(v int) *SchemaTemplateUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchemaTemplateUpdate) SetUpdatedAt(v time.Time) *SchemaTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SchemaTemplateMutation object of the builder.
func (_u *SchemaTemplateUpdate) Mutation() *SchemaTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchemaTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchemaTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchemaTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schematemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchemaTemplateUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := schematemplate.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SchemaTemplate.version": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SchemaTemplate.workspace"`)
	}
	return nil
}

func (_u *SchemaTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schematemplate.Table, schematemplate.Columns, sqlgraph.NewFieldSpec(schematemplate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schematemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(schematemplate.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(schematemplate.FieldDefinition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDefinition(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schematemplate.FieldDefinition, value)
		})
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(schematemplate.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(schematemplate.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schematemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schematemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchemaTemplateUpdateOne is the builder for updating a single SchemaTemplate entity.
type SchemaTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchemaTemplateMutation
}

// SetName sets the "name" field.
func (_u *SchemaTemplateUpdateOne) SetName(v string) *SchemaTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchemaTemplateUpdateOne) SetNillableName(v *string) *SchemaTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SchemaTemplateUpdateOne) SetDescription(v string) *SchemaTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SchemaTemplateUpdateOne) SetNillableDescription(v *string) *SchemaTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *SchemaTemplateUpdateOne) SetDefinition(v jsontext.Value) *SchemaTemplateUpdateOne {
	_u.mutation.SetDefinition(v)
	return _u
}

// AppendDefinition appends value to the "definition" field.
func (_u *SchemaTemplateUpdateOne) AppendDefinition(v jsontext.Value) *SchemaTemplateUpdateOne {
	_u.mutation.AppendDefinition(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *SchemaTemplateUpdateOne) SetVersion(v int) *SchemaTemplateUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SchemaTemplateUpdateOne) SetNillableVersion(v *int) *SchemaTemplateUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SchemaTemplateUpdateOne) AddVersion(v int) *SchemaTemplateUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchemaTemplateUpdateOne) SetUpdatedAt(v time.Time) *SchemaTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SchemaTemplateMutation object of the builder.
func (_u *SchemaTemplateUpdateOne) Mutation() *SchemaTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the SchemaTemplateUpdate builder.
func (_u *SchemaTemplateUpdateOne) Where(ps ...predicate.SchemaTemplate) *SchemaTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchemaTemplateUpdateOne) Select(field string, fields ...string) *SchemaTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SchemaTemplate entity.
func (_u *SchemaTemplateUpdateOne) Save(ctx context.Context) (*SchemaTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaTemplateUpdateOne) SaveX(ctx context.Context) *SchemaTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchemaTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchemaTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schematemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchemaTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := schematemplate.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SchemaTemplate.version": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SchemaTemplate.workspace"`)
	}
	return nil
}

func (_u *SchemaTemplateUpdateOne) sqlSave(ctx context.Context) (_node *SchemaTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schematemplate.Table, schematemplate.Columns, sqlgraph.NewFieldSpec(schematemplate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchemaTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schematemplate.FieldID)
		for _, f := range fields {
			if !schematemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schematemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schematemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(schematemplate.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(schematemplate.FieldDefinition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDefinition(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schematemplate.FieldDefinition, value)
		})
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(schematemplate.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(schematemplate.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schematemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SchemaTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schematemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
