// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"papergo/ent/predicate"
	"papergo/ent/smartfolder"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SmartFolderDelete is the builder for deleting a SmartFolder entity.
type SmartFolderDelete struct {
	config
	hooks    []Hook
	mutation *SmartFolderMutation
}

// Where appends a list predicates to the SmartFolderDelete builder.
func (_d *SmartFolderDelete) Where(ps ...predicate.SmartFolder) *SmartFolderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SmartFolderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SmartFolderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SmartFolderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(smartfolder.Table, sqlgraph.NewFieldSpec(smartfolder.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SmartFolderDeleteOne is the builder for deleting a single SmartFolder entity.
type SmartFolderDeleteOne struct {
	_d *SmartFolderDelete
}

// Where appends a list predicates to the SmartFolderDelete builder.
func (_d *SmartFolderDeleteOne) Where(ps ...predicate.SmartFolder) *SmartFolderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SmartFolderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{smartfolder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SmartFolderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
