// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/predicate"
	"papergo/ent/term"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// TermUpdate is the builder for updating Term entities.
type TermUpdate struct {
	config
	hooks    []Hook
	mutation *TermMutation
}

// Where appends a list predicates to the TermUpdate builder.
func (_u *TermUpdate) Where(ps ...predicate.Term) *TermUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TermUpdate) SetName(v string) *TermUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TermUpdate) SetNillableName(v *string) *TermUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *TermUpdate) SetNormalizedName(v string) *TermUpdate {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *TermUpdate) SetNillableNormalizedName(v *string) *TermUpdate {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *TermUpdate) SetLabels(v map[string]string) *TermUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// SetSynonyms sets the "synonyms" field.
func (_u *TermUpdate) SetSynonyms(v []string) *TermUpdate {
	_u.mutation.SetSynonyms(v)
	return _u
}

// AppendSynonyms appends value to the "synonyms" field.
func (_u *TermUpdate) AppendSynonyms(v []string) *TermUpdate {
	_u.mutation.AppendSynonyms(v)
	return _u
}

// SetDeprecated sets the "deprecated" field.
func (_u *TermUpdate) SetDeprecated(v bool) *TermUpdate {
	_u.mutation.SetDeprecated(v)
	return _u
}

// SetNillableDeprecated sets the "deprecated" field if the given value is not nil.
func (_u *TermUpdate) SetNillableDeprecated(v *bool) *TermUpdate {
	if v != nil {
		_u.SetDeprecated(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *TermUpdate) SetVersion(v int) *TermUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TermUpdate) SetNillableVersion(v *int) *TermUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *TermUpdate) AddVersion(v int) *TermUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TermUpdate) SetUpdatedAt(v time.Time) *TermUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChildIDs adds the "children" edge to the Term entity by IDs.
func (_u *TermUpdate) AddChildIDs(ids ...string) *TermUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Term entity.
func (_u *TermUpdate) AddChildren(v ...*Term) *TermUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the TermMutation object of the builder.
func (_u *TermUpdate) Mutation() *TermMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Term entity.
func (_u *TermUpdate) ClearChildren() *TermUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Term entities by IDs.
func (_u *TermUpdate) RemoveChildIDs(ids ...string) *TermUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Term entities.
func (_u *TermUpdate) RemoveChildren(v ...*Term) *TermUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TermUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TermUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TermUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TermUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TermUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := term.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TermUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := term.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Term.version": %w`, err)}
		}
	}
	if _u.mutation.TermSetCleared() && len(_u.mutation.TermSetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Term.term_set"`)
	}
	return nil
}

func (_u *TermUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(term.Table, term.Columns, sqlgraph.NewFieldSpec(term.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(term.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(term.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(term.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Synonyms(); ok {
		_spec.SetField(term.FieldSynonyms, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSynonyms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, term.FieldSynonyms, value)
		})
	}
	if value, ok := _u.mutation.Deprecated(); ok {
		_spec.SetField(term.FieldDeprecated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(term.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(term.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(term.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   term.ChildrenTable,
			Columns: []string{term.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   term.ChildrenTable,
			Columns: []string{term.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   term.ChildrenTable,
			Columns: []string{term.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{term.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TermUpdateOne is the builder for updating a single Term entity.
type TermUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TermMutation
}

// SetName sets the "name" field.
func (_u *TermUpdateOne) SetName(v string) *TermUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TermUpdateOne) SetNillableName(v *string) *TermUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *TermUpdateOne) SetNormalizedName(v string) *TermUpdateOne {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *TermUpdateOne) SetNillableNormalizedName(v *string) *TermUpdateOne {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *TermUpdateOne) SetLabels(v map[string]string) *TermUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// SetSynonyms sets the "synonyms" field.
func (_u *TermUpdateOne) SetSynonyms(v []string) *TermUpdateOne {
	_u.mutation.SetSynonyms(v)
	return _u
}

// AppendSynonyms appends value to the "synonyms" field.
func (_u *TermUpdateOne) AppendSynonyms(v []string) *TermUpdateOne {
	_u.mutation.AppendSynonyms(v)
	return _u
}

// SetDeprecated sets the "deprecated" field.
func (_u *TermUpdateOne) SetDeprecated(v bool) *TermUpdateOne {
	_u.mutation.SetDeprecated(v)
	return _u
}

// SetNillableDeprecated sets the "deprecated" field if the given value is not nil.
func (_u *TermUpdateOne) SetNillableDeprecated(v *bool) *TermUpdateOne {
	if v != nil {
		_u.SetDeprecated(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *TermUpdateOne) SetVersion(v int) *TermUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TermUpdateOne) SetNillableVersion(v *int) *TermUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *TermUpdateOne) AddVersion(v int) *TermUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TermUpdateOne) SetUpdatedAt(v time.Time) *TermUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChildIDs adds the "children" edge to the Term entity by IDs.
func (_u *TermUpdateOne) AddChildIDs(ids ...string) *TermUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Term entity.
func (_u *TermUpdateOne) AddChildren(v ...*Term) *TermUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the TermMutation object of the builder.
func (_u *TermUpdateOne) Mutation() *TermMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Term entity.
func (_u *TermUpdateOne) ClearChildren() *TermUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Term entities by IDs.
func (_u *TermUpdateOne) RemoveChildIDs(ids ...string) *TermUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Term entities.
func (_u *TermUpdateOne) RemoveChildren(v ...*Term) *TermUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the TermUpdate builder.
func (_u *TermUpdateOne) Where(ps ...predicate.Term) *TermUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TermUpdateOne) Select(field string, fields ...string) *TermUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Term entity.
func (_u *TermUpdateOne) Save(ctx context.Context) (*Term, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TermUpdateOne) SaveX(ctx context.Context) *Term {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TermUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TermUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TermUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := term.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TermUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := term.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Term.version": %w`, err)}
		}
	}
	if _u.mutation.TermSetCleared() && len(_u.mutation.TermSetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Term.term_set"`)
	}
	return nil
}

func (_u *TermUpdateOne) sqlSave(ctx context.Context) (_node *Term, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(term.Table, term.Columns, sqlgraph.NewFieldSpec(term.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Term.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, term.FieldID)
		for _, f := range fields {
			if !term.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != term.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(term.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(term.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(term.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Synonyms(); ok {
		_spec.SetField(term.FieldSynonyms, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSynonyms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, term.FieldSynonyms, value)
		})
	}
	if value, ok := _u.mutation.Deprecated(); ok {
		_spec.SetField(term.FieldDeprecated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(term.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(term.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(term.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   term.ChildrenTable,
			Columns: []string{term.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   term.ChildrenTable,
			Columns: []string{term.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   term.ChildrenTable,
			Columns: []string{term.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Term{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{term.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
