// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/resource"
	"papergo/ent/term"
	"papergo/ent/termgroup"
	"papergo/ent/termset"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TermSetCreate is the builder for creating a TermSet entity.
type TermSetCreate struct {
	config
	mutation *TermSetMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TermSetCreate) SetCreatedAt(v time.Time) *TermSetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableCreatedAt(v *time.Time) *TermSetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *TermSetCreate) SetWorkspaceID(v string) *TermSetCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *TermSetCreate) SetGroupID(v string) *TermSetCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *TermSetCreate) SetKey(v string) *TermSetCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TermSetCreate) SetName(v string) *TermSetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TermSetCreate) SetDescription(v string) *TermSetCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableDescription(v *string) *TermSetCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsOpen sets the "is_open" field.
func (_c *TermSetCreate) SetIsOpen(v bool) *TermSetCreate {
	_c.mutation.SetIsOpen(v)
	return _c
}

// SetNillableIsOpen sets the "is_open" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableIsOpen(v *bool) *TermSetCreate {
	if v != nil {
		_c.SetIsOpen(*v)
	}
	return _c
}

// SetIsKeywords sets the "is_keywords" field.
func (_c *TermSetCreate) SetIsKeywords(v bool) *TermSetCreate {
	_c.mutation.SetIsKeywords(v)
	return _c
}

// SetNillableIsKeywords sets the "is_keywords" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableIsKeywords(v *bool) *TermSetCreate {
	if v != nil {
		_c.SetIsKeywords(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *TermSetCreate) SetVersion(v int) *TermSetCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableVersion(v *int) *TermSetCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TermSetCreate) SetUpdatedAt(v time.Time) *TermSetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableUpdatedAt(v *time.Time) *TermSetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TermSetCreate) SetID(v string) *TermSetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TermSetCreate) SetNillableID(v *string) *TermSetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkspace sets the "workspace" edge to the Resource entity.
func (_c *TermSetCreate) SetWorkspace(v *Resource) *TermSetCreate {
	return _c.SetWorkspaceID(v.ID)
}

// SetGroup sets the "group" edge to the TermGroup entity.
func (_c *TermSetCreate) SetGroup(v *TermGroup) *TermSetCreate {
	return _c.SetGroupID(v.ID)
}

// AddTermIDs adds the "terms" edge to the Term entity by IDs.
func (_c *TermSetCreate) AddTermIDs(ids ...string) *TermSetCreate {
	_c.mutation.AddTermIDs(ids...)
	return _c
}

// AddTerms adds the "terms" edges to the Term entity.
func (_c *TermSetCreate) AddTerms(v ...*Term) *TermSetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTermIDs(ids...)
}

// Mutation returns the TermSetMutation object of the builder.
func (_c *TermSetCreate) Mutation() *TermSetMutation {
	return _c.mutation
}

// Save creates the TermSet in the database.
func (_c *TermSetCreate) Save(ctx context.Context) (*TermSet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TermSetCreate) SaveX(ctx context.Context) *TermSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TermSetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TermSetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TermSetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := termset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := termset.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.IsOpen(); !ok {
		v := termset.DefaultIsOpen
		_c.mutation.SetIsOpen(v)
	}
	if _, ok := _c.mutation.IsKeywords(); !ok {
		v := termset.DefaultIsKeywords
		_c.mutation.SetIsKeywords(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := termset.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := termset.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := termset.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TermSetCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TermSet.created_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "TermSet.workspace_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "TermSet.group_id"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TermSet.key"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TermSet.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "TermSet.description"`)}
	}
	if _, ok := _c.mutation.IsOpen(); !ok {
		return &ValidationError{Name: "is_open", err: errors.New(`ent: missing required field "TermSet.is_open"`)}
	}
	if _, ok := _c.mutation.IsKeywords(); !ok {
		return &ValidationError{Name: "is_keywords", err: errors.New(`ent: missing required field "TermSet.is_keywords"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "TermSet.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := termset.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "TermSet.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TermSet.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := termset.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TermSet.id": %w`, err)}
		}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "TermSet.workspace"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "TermSet.group"`)}
	}
	return nil
}

func (_c *TermSetCreate) sqlSave(ctx context.Context) (*TermSet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TermSet.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TermSetCreate) createSpec() (*TermSet, *sqlgraph.CreateSpec) {
	var (
		_node = &TermSet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(termset.Table, sqlgraph.NewFieldSpec(termset.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(termset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(termset.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(termset.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(termset.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsOpen(); ok {
		_spec.SetField(termset.FieldIsOpen, field.TypeBool, value)
		_node.IsOpen = value
	}
	if value, ok := _c.mutation.IsKeywords(); ok {
		_spec.SetField(termset.FieldIsKeywords, field.TypeBool, value)
		_node.IsKeywords = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(termset.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(termset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   termset.WorkspaceTable,
			Columns: []string{termset.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   termset.GroupTable,
			Columns: []string{termset.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(termgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TermsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   termset.TermsTable,
			Columns: []string{termset.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TermSetCreateBulk is the builder for creating many TermSet entities in bulk.
type TermSetCreateBulk struct {
	config
	err      error
	builders []*TermSetCreate
}

// Save creates the TermSet entities in the database.
func (_c *TermSetCreateBulk) Save(ctx context.Context) ([]*TermSet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TermSet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TermSetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TermSetCreateBulk) SaveX(ctx context.Context) []*TermSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TermSetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TermSetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
