// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/resource"
	"papergo/ent/termgroup"
	"papergo/ent/termset"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TermGroupCreate is the builder for creating a TermGroup entity.
type TermGroupCreate struct {
	config
	mutation *TermGroupMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TermGroupCreate) SetCreatedAt(v time.Time) *TermGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TermGroupCreate) SetNillableCreatedAt(v *time.Time) *TermGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *TermGroupCreate) SetWorkspaceID(v string) *TermGroupCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TermGroupCreate) SetName(v string) *TermGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TermGroupCreate) SetDescription(v string) *TermGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TermGroupCreate) SetNillableDescription(v *string) *TermGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *TermGroupCreate) SetIsSystem(v bool) *TermGroupCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *TermGroupCreate) SetNillableIsSystem(v *bool) *TermGroupCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *TermGroupCreate) SetVersion(v int) *TermGroupCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *TermGroupCreate) SetNillableVersion(v *int) *TermGroupCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TermGroupCreate) SetUpdatedAt(v time.Time) *TermGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TermGroupCreate) SetNillableUpdatedAt(v *time.Time) *TermGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TermGroupCreate) SetID(v string) *TermGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TermGroupCreate) SetNillableID(v *string) *TermGroupCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkspace sets the "workspace" edge to the Resource entity.
func (_c *TermGroupCreate) SetWorkspace(v *Resource) *TermGroupCreate {
	return _c.SetWorkspaceID(v.ID)
}

// AddTermSetIDs adds the "term_sets" edge to the TermSet entity by IDs.
func (_c *TermGroupCreate) AddTermSetIDs(ids ...string) *TermGroupCreate {
	_c.mutation.AddTermSetIDs(ids...)
	return _c
}

// AddTermSets adds the "term_sets" edges to the TermSet entity.
func (_c *TermGroupCreate) AddTermSets(v ...*TermSet) *TermGroupCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTermSetIDs(ids...)
}

// Mutation returns the TermGroupMutation object of the builder.
func (_c *TermGroupCreate) Mutation() *TermGroupMutation {
	return _c.mutation
}

// Save creates the TermGroup in the database.
func (_c *TermGroupCreate) Save(ctx context.Context) (*TermGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TermGroupCreate) SaveX(ctx context.Context) *TermGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TermGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TermGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TermGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := termgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := termgroup.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := termgroup.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := termgroup.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := termgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := termgroup.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TermGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TermGroup.created_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "TermGroup.workspace_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TermGroup.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "TermGroup.description"`)}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "TermGroup.is_system"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "TermGroup.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := termgroup.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "TermGroup.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TermGroup.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := termgroup.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TermGroup.id": %w`, err)}
		}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "TermGroup.workspace"`)}
	}
	return nil
}

func (_c *TermGroupCreate) sqlSave(ctx context.Context) (*TermGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TermGroup.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TermGroupCreate) createSpec() (*TermGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &TermGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(termgroup.Table, sqlgraph.NewFieldSpec(termgroup.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(termgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(termgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(termgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(termgroup.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(termgroup.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(termgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   termgroup.WorkspaceTable,
			Columns: []string{termgroup.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TermSetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   termgroup.TermSetsTable,
			Columns: []string{termgroup.TermSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(termset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TermGroupCreateBulk is the builder for creating many TermGroup entities in bulk.
type TermGroupCreateBulk struct {
	config
	err      error
	builders []*TermGroupCreate
}

// Save creates the TermGroup entities in the database.
func (_c *TermGroupCreateBulk) Save(ctx context.Context) ([]*TermGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TermGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TermGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TermGroupCreateBulk) SaveX(ctx context.Context) []*TermGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TermGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TermGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
