// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"papergo/ent/predicate"
	"papergo/ent/workflowtrigger"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowTriggerUpdate is the builder for updating WorkflowTrigger entities.
type WorkflowTriggerUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowTriggerMutation
}

// Where appends a list predicates to the WorkflowTriggerUpdate builder.
func (_u *WorkflowTriggerUpdate) Where(ps ...predicate.WorkflowTrigger) *WorkflowTriggerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNextAt sets the "next_at" field.
func (_u *WorkflowTriggerUpdate) SetNextAt(v time.Time) *WorkflowTriggerUpdate {
	_u.mutation.SetNextAt(v)
	return _u
}

// SetNillableNextAt sets the "next_at" field if the given value is not nil.
func (_u *WorkflowTriggerUpdate) SetNillableNextAt(v *time.Time) *WorkflowTriggerUpdate {
	if v != nil {
		_u.SetNextAt(*v)
	}
	return _u
}

// ClearNextAt clears the value of the "next_at" field.
func (_u *WorkflowTriggerUpdate) ClearNextAt() *WorkflowTriggerUpdate {
	_u.mutation.ClearNextAt()
	return _u
}

// Mutation returns the WorkflowTriggerMutation object of the builder.
func (_u *WorkflowTriggerUpdate) Mutation() *WorkflowTriggerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowTriggerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowTriggerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowTriggerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowTriggerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkflowTriggerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflowtrigger.Table, workflowtrigger.Columns, sqlgraph.NewFieldSpec(workflowtrigger.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CollectionIDCleared() {
		_spec.ClearField(workflowtrigger.FieldCollectionID, field.TypeString)
	}
	if value, ok := _u.mutation.NextAt(); ok {
		_spec.SetField(workflowtrigger.FieldNextAt, field.TypeTime, value)
	}
	if _u.mutation.NextAtCleared() {
		_spec.ClearField(workflowtrigger.FieldNextAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowtrigger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowTriggerUpdateOne is the builder for updating a single WorkflowTrigger entity.
type WorkflowTriggerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowTriggerMutation
}

// SetNextAt sets the "next_at" field.
func (_u *WorkflowTriggerUpdateOne) SetNextAt(v time.Time) *WorkflowTriggerUpdateOne {
	_u.mutation.SetNextAt(v)
	return _u
}

// SetNillableNextAt sets the "next_at" field if the given value is not nil.
func (_u *WorkflowTriggerUpdateOne) SetNillableNextAt(v *time.Time) *WorkflowTriggerUpdateOne {
	if v != nil {
		_u.SetNextAt(*v)
	}
	return _u
}

// ClearNextAt clears the value of the "next_at" field.
func (_u *WorkflowTriggerUpdateOne) ClearNextAt() *WorkflowTriggerUpdateOne {
	_u.mutation.ClearNextAt()
	return _u
}

// Mutation returns the WorkflowTriggerMutation object of the builder.
func (_u *WorkflowTriggerUpdateOne) Mutation() *WorkflowTriggerMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowTriggerUpdate builder.
func (_u *WorkflowTriggerUpdateOne) Where(ps ...predicate.WorkflowTrigger) *WorkflowTriggerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowTriggerUpdateOne) Select(field string, fields ...string) *WorkflowTriggerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowTrigger entity.
func (_u *WorkflowTriggerUpdateOne) Save(ctx context.Context) (*WorkflowTrigger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowTriggerUpdateOne) SaveX(ctx context.Context) *WorkflowTrigger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowTriggerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowTriggerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkflowTriggerUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowTrigger, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflowtrigger.Table, workflowtrigger.Columns, sqlgraph.NewFieldSpec(workflowtrigger.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowTrigger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowtrigger.FieldID)
		for _, f := range fields {
			if !workflowtrigger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowtrigger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CollectionIDCleared() {
		_spec.ClearField(workflowtrigger.FieldCollectionID, field.TypeString)
	}
	if value, ok := _u.mutation.NextAt(); ok {
		_spec.SetField(workflowtrigger.FieldNextAt, field.TypeTime, value)
	}
	if _u.mutation.NextAtCleared() {
		_spec.ClearField(workflowtrigger.FieldNextAt, field.TypeTime)
	}
	_node = &WorkflowTrigger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowtrigger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
