// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"papergo/ent/workflowrunitem"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WorkflowRunItem is the model entity for the WorkflowRunItem schema.
type WorkflowRunItem struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID string `json:"item_id,omitempty"`
	// Position holds the value of the "position" field.
	Position     int `json:"position,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowRunItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowrunitem.FieldPosition:
			values[i] = new(sql.NullInt64)
		case workflowrunitem.FieldID, workflowrunitem.FieldRunID, workflowrunitem.FieldItemID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowRunItem fields.
func (_m *WorkflowRunItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowrunitem.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case workflowrunitem.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case workflowrunitem.FieldItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = value.String
			}
		case workflowrunitem.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowRunItem.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowRunItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WorkflowRunItem.
// Note that you need to call WorkflowRunItem.Unwrap() before calling this method if this WorkflowRunItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowRunItem) Update() *WorkflowRunItemUpdateOne {
	return NewWorkflowRunItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowRunItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowRunItem) Unwrap() *WorkflowRunItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowRunItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowRunItem) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowRunItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(_m.ItemID)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowRunItems is a parsable slice of WorkflowRunItem.
type WorkflowRunItems []*WorkflowRunItem
