// Code generated by ent, DO NOT EDIT.

package schemarevision

import (
	"papergo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// ContainerID applies equality check predicate on the "container_id" field. It's identical to ContainerIDEQ.
func ContainerID(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldContainerID, v))
}

// RevisionNumber applies equality check predicate on the "revision_number" field. It's identical to RevisionNumberEQ.
func RevisionNumber(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldRevisionNumber, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// ContainerIDEQ applies the EQ predicate on the "container_id" field.
func ContainerIDEQ(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldContainerID, v))
}

// ContainerIDNEQ applies the NEQ predicate on the "container_id" field.
func ContainerIDNEQ(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNEQ(FieldContainerID, v))
}

// ContainerIDIn applies the In predicate on the "container_id" field.
func ContainerIDIn(vs ...string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldIn(FieldContainerID, vs...))
}

// ContainerIDNotIn applies the NotIn predicate on the "container_id" field.
func ContainerIDNotIn(vs ...string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNotIn(FieldContainerID, vs...))
}

// ContainerIDGT applies the GT predicate on the "container_id" field.
func ContainerIDGT(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGT(FieldContainerID, v))
}

// ContainerIDGTE applies the GTE predicate on the "container_id" field.
func ContainerIDGTE(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGTE(FieldContainerID, v))
}

// ContainerIDLT applies the LT predicate on the "container_id" field.
func ContainerIDLT(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLT(FieldContainerID, v))
}

// ContainerIDLTE applies the LTE predicate on the "container_id" field.
func ContainerIDLTE(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLTE(FieldContainerID, v))
}

// ContainerIDContains applies the Contains predicate on the "container_id" field.
func ContainerIDContains(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldContains(FieldContainerID, v))
}

// ContainerIDHasPrefix applies the HasPrefix predicate on the "container_id" field.
func ContainerIDHasPrefix(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldHasPrefix(FieldContainerID, v))
}

// ContainerIDHasSuffix applies the HasSuffix predicate on the "container_id" field.
func ContainerIDHasSuffix(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldHasSuffix(FieldContainerID, v))
}

// ContainerIDEqualFold applies the EqualFold predicate on the "container_id" field.
func ContainerIDEqualFold(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEqualFold(FieldContainerID, v))
}

// ContainerIDContainsFold applies the ContainsFold predicate on the "container_id" field.
func ContainerIDContainsFold(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldContainsFold(FieldContainerID, v))
}

// RevisionNumberEQ applies the EQ predicate on the "revision_number" field.
func RevisionNumberEQ(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldRevisionNumber, v))
}

// RevisionNumberNEQ applies the NEQ predicate on the "revision_number" field.
func RevisionNumberNEQ(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNEQ(FieldRevisionNumber, v))
}

// RevisionNumberIn applies the In predicate on the "revision_number" field.
func RevisionNumberIn(vs ...int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldIn(FieldRevisionNumber, vs...))
}

// RevisionNumberNotIn applies the NotIn predicate on the "revision_number" field.
func RevisionNumberNotIn(vs ...int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNotIn(FieldRevisionNumber, vs...))
}

// RevisionNumberGT applies the GT predicate on the "revision_number" field.
func RevisionNumberGT(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGT(FieldRevisionNumber, v))
}

// RevisionNumberGTE applies the GTE predicate on the "revision_number" field.
func RevisionNumberGTE(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGTE(FieldRevisionNumber, v))
}

// RevisionNumberLT applies the LT predicate on the "revision_number" field.
func RevisionNumberLT(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLT(FieldRevisionNumber, v))
}

// RevisionNumberLTE applies the LTE predicate on the "revision_number" field.
func RevisionNumberLTE(v int) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLTE(FieldRevisionNumber, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.FieldContainsFold(FieldCreatedBy, v))
}

// HasContainer applies the HasEdge predicate on the "container" edge.
func HasContainer() predicate.SchemaRevision {
	return predicate.SchemaRevision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ContainerTable, ContainerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContainerWith applies the HasEdge predicate on the "container" edge with a given conditions (other predicates).
func HasContainerWith(preds ...predicate.Resource) predicate.SchemaRevision {
	return predicate.SchemaRevision(func(s *sql.Selector) {
		step := newContainerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.SchemaRevision {
	return predicate.SchemaRevision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.ItemRevision) predicate.SchemaRevision {
	return predicate.SchemaRevision(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SchemaRevision) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SchemaRevision) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SchemaRevision) predicate.SchemaRevision {
	return predicate.SchemaRevision(sql.NotPredicates(p))
}
