// Code generated by ent, DO NOT EDIT.

package resource

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the resource type in the database.
	Label = "resource"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldContainerID holds the string denoting the container_id field in the database.
	FieldContainerID = "container_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldValues holds the string denoting the values field in the database.
	FieldValues = "values"
	// FieldInheritPermissions holds the string denoting the inherit_permissions field in the database.
	FieldInheritPermissions = "inherit_permissions"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldHeadRevisionID holds the string denoting the head_revision_id field in the database.
	FieldHeadRevisionID = "head_revision_id"
	// FieldPublishedRevisionID holds the string denoting the published_revision_id field in the database.
	FieldPublishedRevisionID = "published_revision_id"
	// FieldSchemaHeadID holds the string denoting the schema_head_id field in the database.
	FieldSchemaHeadID = "schema_head_id"
	// FieldNextRevisionNumber holds the string denoting the next_revision_number field in the database.
	FieldNextRevisionNumber = "next_revision_number"
	// FieldPublishingEnabled holds the string denoting the publishing_enabled field in the database.
	FieldPublishingEnabled = "publishing_enabled"
	// FieldWebdavEnabled holds the string denoting the webdav_enabled field in the database.
	FieldWebdavEnabled = "webdav_enabled"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldNameKey holds the string denoting the name_key field in the database.
	FieldNameKey = "name_key"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeContainedItems holds the string denoting the contained_items edge name in mutations.
	EdgeContainedItems = "contained_items"
	// EdgeContainer holds the string denoting the container edge name in mutations.
	EdgeContainer = "container"
	// EdgeDefinitions holds the string denoting the definitions edge name in mutations.
	EdgeDefinitions = "definitions"
	// EdgeGrants holds the string denoting the grants edge name in mutations.
	EdgeGrants = "grants"
	// EdgeOutgoing holds the string denoting the outgoing edge name in mutations.
	EdgeOutgoing = "outgoing"
	// EdgeIncoming holds the string denoting the incoming edge name in mutations.
	EdgeIncoming = "incoming"
	// EdgePublications holds the string denoting the publications edge name in mutations.
	EdgePublications = "publications"
	// EdgeBlobs holds the string denoting the blobs edge name in mutations.
	EdgeBlobs = "blobs"
	// EdgeRevisions holds the string denoting the revisions edge name in mutations.
	EdgeRevisions = "revisions"
	// EdgeSchemaRevisions holds the string denoting the schema_revisions edge name in mutations.
	EdgeSchemaRevisions = "schema_revisions"
	// EdgeHeadRevision holds the string denoting the head_revision edge name in mutations.
	EdgeHeadRevision = "head_revision"
	// EdgePublishedRevision holds the string denoting the published_revision edge name in mutations.
	EdgePublishedRevision = "published_revision"
	// EdgeSchemaHead holds the string denoting the schema_head edge name in mutations.
	EdgeSchemaHead = "schema_head"
	// Table holds the table name of the resource in the database.
	Table = "resources"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "resources"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "parent_id"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "resources"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "parent_id"
	// ContainedItemsTable is the table that holds the contained_items relation/edge.
	ContainedItemsTable = "resources"
	// ContainedItemsColumn is the table column denoting the contained_items relation/edge.
	ContainedItemsColumn = "container_id"
	// ContainerTable is the table that holds the container relation/edge.
	ContainerTable = "resources"
	// ContainerColumn is the table column denoting the container relation/edge.
	ContainerColumn = "container_id"
	// DefinitionsTable is the table that holds the definitions relation/edge.
	DefinitionsTable = "field_definitions"
	// DefinitionsInverseTable is the table name for the FieldDefinition entity.
	// It exists in this package in order to avoid circular dependency with the "fielddefinition" package.
	DefinitionsInverseTable = "field_definitions"
	// DefinitionsColumn is the table column denoting the definitions relation/edge.
	DefinitionsColumn = "container_id"
	// GrantsTable is the table that holds the grants relation/edge.
	GrantsTable = "grants"
	// GrantsInverseTable is the table name for the Grant entity.
	// It exists in this package in order to avoid circular dependency with the "grant" package.
	GrantsInverseTable = "grants"
	// GrantsColumn is the table column denoting the grants relation/edge.
	GrantsColumn = "resource_id"
	// OutgoingTable is the table that holds the outgoing relation/edge.
	OutgoingTable = "relationships"
	// OutgoingInverseTable is the table name for the Relationship entity.
	// It exists in this package in order to avoid circular dependency with the "relationship" package.
	OutgoingInverseTable = "relationships"
	// OutgoingColumn is the table column denoting the outgoing relation/edge.
	OutgoingColumn = "source_id"
	// IncomingTable is the table that holds the incoming relation/edge.
	IncomingTable = "relationships"
	// IncomingInverseTable is the table name for the Relationship entity.
	// It exists in this package in order to avoid circular dependency with the "relationship" package.
	IncomingInverseTable = "relationships"
	// IncomingColumn is the table column denoting the incoming relation/edge.
	IncomingColumn = "target_id"
	// PublicationsTable is the table that holds the publications relation/edge.
	PublicationsTable = "publications"
	// PublicationsInverseTable is the table name for the Publication entity.
	// It exists in this package in order to avoid circular dependency with the "publication" package.
	PublicationsInverseTable = "publications"
	// PublicationsColumn is the table column denoting the publications relation/edge.
	PublicationsColumn = "item_id"
	// BlobsTable is the table that holds the blobs relation/edge.
	BlobsTable = "blobs"
	// BlobsInverseTable is the table name for the Blob entity.
	// It exists in this package in order to avoid circular dependency with the "blob" package.
	BlobsInverseTable = "blobs"
	// BlobsColumn is the table column denoting the blobs relation/edge.
	BlobsColumn = "item_id"
	// RevisionsTable is the table that holds the revisions relation/edge.
	RevisionsTable = "item_revisions"
	// RevisionsInverseTable is the table name for the ItemRevision entity.
	// It exists in this package in order to avoid circular dependency with the "itemrevision" package.
	RevisionsInverseTable = "item_revisions"
	// RevisionsColumn is the table column denoting the revisions relation/edge.
	RevisionsColumn = "item_id"
	// SchemaRevisionsTable is the table that holds the schema_revisions relation/edge.
	SchemaRevisionsTable = "schema_revisions"
	// SchemaRevisionsInverseTable is the table name for the SchemaRevision entity.
	// It exists in this package in order to avoid circular dependency with the "schemarevision" package.
	SchemaRevisionsInverseTable = "schema_revisions"
	// SchemaRevisionsColumn is the table column denoting the schema_revisions relation/edge.
	SchemaRevisionsColumn = "container_id"
	// HeadRevisionTable is the table that holds the head_revision relation/edge.
	HeadRevisionTable = "resources"
	// HeadRevisionInverseTable is the table name for the ItemRevision entity.
	// It exists in this package in order to avoid circular dependency with the "itemrevision" package.
	HeadRevisionInverseTable = "item_revisions"
	// HeadRevisionColumn is the table column denoting the head_revision relation/edge.
	HeadRevisionColumn = "head_revision_id"
	// PublishedRevisionTable is the table that holds the published_revision relation/edge.
	PublishedRevisionTable = "resources"
	// PublishedRevisionInverseTable is the table name for the ItemRevision entity.
	// It exists in this package in order to avoid circular dependency with the "itemrevision" package.
	PublishedRevisionInverseTable = "item_revisions"
	// PublishedRevisionColumn is the table column denoting the published_revision relation/edge.
	PublishedRevisionColumn = "published_revision_id"
	// SchemaHeadTable is the table that holds the schema_head relation/edge.
	SchemaHeadTable = "resources"
	// SchemaHeadInverseTable is the table name for the SchemaRevision entity.
	// It exists in this package in order to avoid circular dependency with the "schemarevision" package.
	SchemaHeadInverseTable = "schema_revisions"
	// SchemaHeadColumn is the table column denoting the schema_head relation/edge.
	SchemaHeadColumn = "schema_head_id"
)

// Columns holds all SQL columns for resource fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldWorkspaceID,
	FieldParentID,
	FieldContainerID,
	FieldKind,
	FieldName,
	FieldTags,
	FieldValues,
	FieldInheritPermissions,
	FieldVersion,
	FieldHeadRevisionID,
	FieldPublishedRevisionID,
	FieldSchemaHeadID,
	FieldNextRevisionNumber,
	FieldPublishingEnabled,
	FieldWebdavEnabled,
	FieldUpdatedAt,
	FieldScopeID,
	FieldNameKey,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	WorkspaceIDValidator func(string) error
	// ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	ParentIDValidator func(string) error
	// ContainerIDValidator is a validator for the "container_id" field. It is called by the builders before save.
	ContainerIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultValues holds the default value on creation for the "values" field.
	DefaultValues map[string]interface{}
	// DefaultInheritPermissions holds the default value on creation for the "inherit_permissions" field.
	DefaultInheritPermissions bool
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
	// DefaultNextRevisionNumber holds the default value on creation for the "next_revision_number" field.
	DefaultNextRevisionNumber int
	// NextRevisionNumberValidator is a validator for the "next_revision_number" field. It is called by the builders before save.
	NextRevisionNumberValidator func(int) error
	// DefaultPublishingEnabled holds the default value on creation for the "publishing_enabled" field.
	DefaultPublishingEnabled bool
	// DefaultWebdavEnabled holds the default value on creation for the "webdav_enabled" field.
	DefaultWebdavEnabled bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ScopeIDValidator is a validator for the "scope_id" field. It is called by the builders before save.
	ScopeIDValidator func(string) error
	// NameKeyValidator is a validator for the "name_key" field. It is called by the builders before save.
	NameKeyValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindWorkspace Kind = "workspace"
	KindList      Kind = "list"
	KindLibrary   Kind = "library"
	KindFolder    Kind = "folder"
	KindItem      Kind = "item"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindWorkspace, KindList, KindLibrary, KindFolder, KindItem:
		return nil
	default:
		return fmt.Errorf("resource: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Resource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByWorkspaceID orders the results by the workspace_id field.
func ByWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceID, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByContainerID orders the results by the container_id field.
func ByContainerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContainerID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByInheritPermissions orders the results by the inherit_permissions field.
func ByInheritPermissions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInheritPermissions, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByHeadRevisionID orders the results by the head_revision_id field.
func ByHeadRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadRevisionID, opts...).ToFunc()
}

// ByPublishedRevisionID orders the results by the published_revision_id field.
func ByPublishedRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedRevisionID, opts...).ToFunc()
}

// BySchemaHeadID orders the results by the schema_head_id field.
func BySchemaHeadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaHeadID, opts...).ToFunc()
}

// ByNextRevisionNumber orders the results by the next_revision_number field.
func ByNextRevisionNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRevisionNumber, opts...).ToFunc()
}

// ByPublishingEnabled orders the results by the publishing_enabled field.
func ByPublishingEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishingEnabled, opts...).ToFunc()
}

// ByWebdavEnabled orders the results by the webdav_enabled field.
func ByWebdavEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavEnabled, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByNameKey orders the results by the name_key field.
func ByNameKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameKey, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByContainedItemsCount orders the results by contained_items count.
func ByContainedItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContainedItemsStep(), opts...)
	}
}

// ByContainedItems orders the results by contained_items terms.
func ByContainedItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContainedItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByContainerField orders the results by container field.
func ByContainerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContainerStep(), sql.OrderByField(field, opts...))
	}
}

// ByDefinitionsCount orders the results by definitions count.
func ByDefinitionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDefinitionsStep(), opts...)
	}
}

// ByDefinitions orders the results by definitions terms.
func ByDefinitions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDefinitionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGrantsCount orders the results by grants count.
func ByGrantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGrantsStep(), opts...)
	}
}

// ByGrants orders the results by grants terms.
func ByGrants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOutgoingCount orders the results by outgoing count.
func ByOutgoingCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOutgoingStep(), opts...)
	}
}

// ByOutgoing orders the results by outgoing terms.
func ByOutgoing(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutgoingStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIncomingCount orders the results by incoming count.
func ByIncomingCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIncomingStep(), opts...)
	}
}

// ByIncoming orders the results by incoming terms.
func ByIncoming(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIncomingStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPublicationsCount orders the results by publications count.
func ByPublicationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPublicationsStep(), opts...)
	}
}

// ByPublications orders the results by publications terms.
func ByPublications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPublicationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBlobsCount orders the results by blobs count.
func ByBlobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBlobsStep(), opts...)
	}
}

// ByBlobs orders the results by blobs terms.
func ByBlobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRevisionsCount orders the results by revisions count.
func ByRevisionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRevisionsStep(), opts...)
	}
}

// ByRevisions orders the results by revisions terms.
func ByRevisions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRevisionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySchemaRevisionsCount orders the results by schema_revisions count.
func BySchemaRevisionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSchemaRevisionsStep(), opts...)
	}
}

// BySchemaRevisions orders the results by schema_revisions terms.
func BySchemaRevisions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchemaRevisionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHeadRevisionField orders the results by head_revision field.
func ByHeadRevisionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHeadRevisionStep(), sql.OrderByField(field, opts...))
	}
}

// ByPublishedRevisionField orders the results by published_revision field.
func ByPublishedRevisionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPublishedRevisionStep(), sql.OrderByField(field, opts...))
	}
}

// BySchemaHeadField orders the results by schema_head field.
func BySchemaHeadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchemaHeadStep(), sql.OrderByField(field, opts...))
	}
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newContainedItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ContainedItemsTable, ContainedItemsColumn),
	)
}
func newContainerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ContainerTable, ContainerColumn),
	)
}
func newDefinitionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DefinitionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DefinitionsTable, DefinitionsColumn),
	)
}
func newGrantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GrantsTable, GrantsColumn),
	)
}
func newOutgoingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutgoingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OutgoingTable, OutgoingColumn),
	)
}
func newIncomingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IncomingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IncomingTable, IncomingColumn),
	)
}
func newPublicationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PublicationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PublicationsTable, PublicationsColumn),
	)
}
func newBlobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BlobsTable, BlobsColumn),
	)
}
func newRevisionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RevisionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RevisionsTable, RevisionsColumn),
	)
}
func newSchemaRevisionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchemaRevisionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SchemaRevisionsTable, SchemaRevisionsColumn),
	)
}
func newHeadRevisionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HeadRevisionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, HeadRevisionTable, HeadRevisionColumn),
	)
}
func newPublishedRevisionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PublishedRevisionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PublishedRevisionTable, PublishedRevisionColumn),
	)
}
func newSchemaHeadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchemaHeadInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SchemaHeadTable, SchemaHeadColumn),
	)
}
